### ISSUE TITLE
Request + minor bug

### ISSUE THREAD

**Issue by hasanas83V2001** [SirBlobman/CombatLogX#10]
Would it be possible to have an npc spawned without having to install citizens? A different combattag plugin has this and it's really nice as I don't want to install a large plugin like citizens, and I really love this plugin!

My bug report: When using color codes in the "you are not in combat", they work fine in chat, but in the boss bar, it doesn't work. This is what I mean: http://i.imgur.com/AoaFD18.png

**Comment by SirBlobman** [comment]
My own custom NPC would be difficult but I can try

I will try to fix the boss bar bug

**Comment by SirBlobman** [comment]
Fixed boss bar bug in 5.0.4 Release
