### ISSUE TITLE
Ender pearl issue

### ISSUE THREAD

**Issue by BakaDesuDesu** [SirBlobman/CombatLogX#100]
During the pvp using of ender pearl to safe zone the following problem appears (refer to the video attached)

Versions:
Core: Paper 1.14.4
CombatLogX: v9.9.1.4
Active expansions: Cheat prevention, Towny Compatibility
Towny:  0.94.0.0

https://youtu.be/LzzxQ5u_zTo

**Comment by SirBlobman** [comment]
Should be fixed in 10.0.0.0 builds. If not please reopen this issue.
