### ISSUE TITLE
CheatPrevention expansion cfg not created v9.9.1.5

### ISSUE THREAD

**Issue by gweeii** [SirBlobman/CombatLogX#101]
**Describe the bug**
The "CheatPrevention" expansion config file have not been created

**To Reproduce**
I simply deleted the plugin with all the files and installed version 9.9.1.5

**Screenshots**
https://gyazo.com/71dd83c766f9456702907e88101d8b56

**Minecraft Version**
 - Paper-192 (MC: 1.14.4)

**CombatLogX Version:**
 - v9.9.1.5

**Comment by SirBlobman** [comment]
Fixed in 9.9.1.7
