### ISSUE TITLE
Combat timer doesn't end

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#104]
Spigot 1.14.4 (Jenkins 2477)
CombatLogX 10.0.0.0-beta

**Describe the bug**
Attacking mobs places player into combat, but then combat state never times out.
```
[17:05:49] [Craft Scheduler Thread - 25/WARN]: [CombatLogX] Plugin CombatLogX v10.0.0.0-Beta generated an exception while executing task 5975
java.lang.IllegalStateException: PlayerCombatTimerChangeEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511) ~[spigot-1.14.4.jar-2019-09-30-1817:git-Spigot-94af569-a3fdef8]
        at com.SirBlobman.combatlogx.utility.CombatManager.run(CombatManager.java:190) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar-2019-09-30-1817:git-Spigot-94af569-a3fdef8]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar-2019-09-30-1817:git-Spigot-94af569-a3fdef8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by SirBlobman** [comment]
I'll look into it, thanks for the info

**Comment by jamoreq** [comment]
Expansion 'Notifier' also no loading for expansions, config doesn't created.

**Comment by SlimeDog** [comment]
This issue remains in CLX 10.0.0.0-beta1

**Comment by SirBlobman** [comment]
@jamoreq Notifier is not created yet, here is a list of features: https://github.com/SirBlobman/CombatLogX/releases/tag/10.0.0.0-beta1

@SlimeDog thanks, I'll fix it soon

**Comment by jamoreq** [comment]
when this will be fixed?

**Comment by SirBlobman** [comment]
@jamoreq working on it, this is a beta build so if you need to actually use CombatLogX please go back to the latest version on Spigot

**Comment by jamoreq** [comment]
Beta version only have options on config etc. ?
In game plugin is not it works, no errors etc

**Comment by SirBlobman** [comment]
@jamoreq @SlimeDog 
try Beta 2 when you have time :)

**Comment by SlimeDog** [comment]
I don't see beta2. Broken build 32 was up briefly, but is now gone. Is there somewhere else to look?

**Comment by SlimeDog** [comment]
Beta2:
I see a combat timer on the announcer bar, but
- It does not expire when the combat target dies, but continues to count down. I would like it to expire immediately when the combat target dies. Is this related to
```
combat:
  timer: 15
```
What value will cause it to expire when the combat target dies?

**Comment by SirBlobman** [comment]
@SlimeDog Did you get the correct one from https://github.com/SirBlobman/CombatLogX/releases ?

The combat timer should be going down, if not please reset your configs

**Comment by SlimeDog** [comment]
The timer counts down. But it should immediately set to 0 when the combat target dies.

**Comment by SirBlobman** [comment]
> Yes, I got the "right one" (even though were are two Beta2 releases).
> 
> The timer counts down. But it should immediately set to 0 when the combat target dies. Right? I need to be able to get to the next attack immediately.

There should be a config option called `untag.on-enemy-death`. It is false by default

**Comment by SlimeDog** [comment]
Thanks. That fixes it, of course. Why would it be false by default?

**Comment by SirBlobman** [comment]
> Thanks. That fixes it, of course. Why would it be false by default?

Not sure, I'll put a poll on my discord to see what people prefer

**Comment by SirBlobman** [comment]
@SlimeDog now that you mention it, the CI is better for beta builders. You can get them from there instead of waiting for me to make a GitHub release, and I even included the build number in the CombatLogX version

https://ci.codemc.io/job/SirBlobman/job/CombatLogX/lastSuccessfulBuild/artifact/builder/build/
