### ISSUE TITLE
CheatPrevention commands bug

### ISSUE THREAD

**Issue by eUipKh** [SirBlobman/CombatLogX#111]
**Describe the bug**
Players are unable to use whitelisted command properly, they can only use the command without any argument.

**To Reproduce**
Set commands.whitelist: true
Set commands.commands: [/ac]
Get tagged and use the command /ac <argument>

**Expected behavior**

**Screenshots**
- https://imgur.com/fIb3aVE
- https://imgur.com/LOOgBQl
- https://imgur.com/097uEv3

**Minecraft Version**
- https://imgur.com/GVSogtL

**CombatLogX Version:**
- https://imgur.com/GVSogtL

**Additional context**
-

**Comment by SirBlobman** [comment]
@eUipKh would you be willing to test beta builds? This bug seems fixed in beta but I want to confirm before a full release version

**Comment by eUipKh** [comment]
Yes, if that helps ;)
- Sorry for the late response

**Comment by SirBlobman** [comment]
@eUipKh That's fine, I don't normally check GitHub as often as my discord anyways

You can find beta builds on the #jenkins-updates channel in that Discord

**Comment by eUipKh** [comment]
The plugin load fine with no error but when someone get tagged I got this error spammed:
https://gist.github.com/eUipKh/c1e3fc7c0ccffa5766859d97bd4a321e

Server info: 
https://gist.github.com/eUipKh/806ac03af6783421547e0f9a016dbc01

**Comment by SirBlobman** [comment]
@eUipKh This issue should be fixed in CombatLogX 9.9.2.2
