### ISSUE TITLE
More customization such as toggling where the combat information shows

### ISSUE THREAD

**Issue by Jadiction** [SirBlobman/CombatLogX#115]
**What Minecraft version are you currently using?**
Paper 1.15.2

**What is your feature request?**
The ability to toggle the chat messages, boss bar, scoreboard and the information above the hot-bar. I find having every one of those showing the same information unnecessary and redundant, thus I'd like the ability to choose one or two rather than being forced to use them all.

The option to customize each message in every method would be nice as well (although I can't recall if this was a thing or not, if it's added, ignore this)

**Comment by SirBlobman** [comment]
All messages can be modified in the language.yml. You can disable the boss bar, action bar, or scoreboard by modifying the config for the Notifier Expansion
