### ISSUE TITLE
Bug pickup items.

### ISSUE THREAD

**Issue by Haczyn** [SirBlobman/CombatLogX#119]
**Describe the bug**
Player not marked, not in combat. Can't pick up items. For example when player join on server and want do thier stuff, he cant, beacuse in some cases he cant break blocks or pick up items. I have turned off it in conf file. they arent in combat. today i had a few report about it. To fix it player have to do reload. I think its visual bug, because when i teleported to my player he had picked up all items and send me screenshot about he didnt pickup that. 
**To Reproduce**
How can I see the issue for myself? Please explain how it happened.
Fix it
**Expected behavior**
Pick up items destory blocks. 
**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![2020-04-19_01 21 56](https://user-images.githubusercontent.com/60531623/79677817-66ce7b00-81f5-11ea-930e-0c4b79e6c6e3.png)
![2020-04-18_18 33 23](https://user-images.githubusercontent.com/60531623/79677818-6a620200-81f5-11ea-87c3-7b432bc9c31e.png)
![2020-04-18_00 59 41](https://user-images.githubusercontent.com/60531623/79677819-6c2bc580-81f5-11ea-8b07-f852d173e6a1.png)
![2020-04-18_00 59 41](https://user-images.githubusercontent.com/60531623/79677824-7221a680-81f5-11ea-8b99-e31a7aafb0c0.png)
![Uploading 2020-04-18_18.33.23.png…]()

![IMG_20200417_112119](https://user-images.githubusercontent.com/60531623/79677810-5c13e600-81f5-11ea-92ed-933d2f2691a1.jpg)

**Minecraft Version**
Full Version: git-Paper-192 (MC: 1.15.2)
>.... [03:48:21 INFO]: Bukkit Version: 1.15.2-R0.1-SNAPSHOT
>.... [03:48:21 INFO]: Minecraft Version: 1.15.2
>.... [03:48:21 INFO]: NMS Version: 1_15_R1
>.... [03:48:21 INFO]:
>.... [03:48:21 INFO]: CombatLogX by SirBlobman
>.... [03:48:21 INFO]:
>.... [03:48:21 INFO]: Latest Spigot Version: v9.9.3.1
>.... [03:48:21 INFO]: Installed Version: v9.9.3.1
>.... [03:48:21 INFO]:
>.... [03:48:21 INFO]: Getting expansion versions...
>.... [03:48:21 INFO]:
>.... [03:48:21 INFO]: Notifier v14.15
>.... [03:48:21 INFO]: Placeholder Compatibility v14.4
>.... [03:48:21 INFO]: Cheat Prevention v14.17
>.... [03:48:21 INFO]: WorldGuard Compatibility v14.13
>.... [03:48:21 INFO]: NotCombatLogX v14.4
>.... [03:48:21 INFO]: Newbie Helper v14.5

**Comment by SirBlobman** [comment]
Unfortunately I can't do anything about this bug. Client-side ghost entities cannot be removed by any plugin. Also, CombatLogX ensures that players are in combat before cancelling any events, as can be seen in the Cheat Prevention expansion code:

https://github.com/SirBlobman/CombatLogX/blob/old/9.0.0.0/expansion/CheatPrevention/src/main/java/com/SirBlobman/expansion/cheatprevention/listener/ListenNewItemPickup.java#L20-L32

**Comment by Haczyn** [comment]
Dude but players cant dig too... It isnt only visual bug.
