### ISSUE TITLE
Not checking for updates?

### ISSUE THREAD

**Issue by hasanas83V2001** [SirBlobman/CombatLogX#12]
I only have CombatLogX as the only plugin and I get this (some other plugins have the same issue atm):
http://imgur.com/a/vNhRM
Also how do I just allowed all potions during combat? Whenever I remove that list it just gets reset

**Comment by SirBlobman** [comment]
1) I'll look into the issue 
2) You cannot remove a list. You have to set it to `blocked potions: []`

**Comment by hasanas83V2001** [comment]
Okay thanks, as for the not updating, it was on spigots end but it's fixed now!

**Comment by SirBlobman** [comment]
Yeah, 5.1.1 (Will release thursday, you can download dev builds here) will fix the update checker issues
