### ISSUE TITLE
Log to chat and boss bar issue 

### ISSUE THREAD

**Issue by HungryHobos** [SirBlobman/CombatLogX#125]
Unable to stop from broadcasting in chat when logged and no boss bar showing up. Set to true. idk if im missing something in the config or what but the count down timer is to much for chat.  Just need it to be boss bar only cant shut off chat messages. :/ probably my end but would appreciate some help thanks
[config.txt](https://github.com/SirBlobman/CombatLogX/files/4871189/config.txt)

**Comment by HungryHobos** [comment]
Update i figured it out is just shows them in chat instead on on screen now

**Comment by SirBlobman** [comment]
Please follow the correct bug report format and reopen the issue once that is finished.
