### ISSUE TITLE
Add option to turn the world blacklist in a world whitelist

### ISSUE THREAD

**Issue by Drc-DEV** [SirBlobman/CombatLogX#127]
Spigot 1.15.2 - CLX 10.0.0.0.Beta-243

Add an option like "use-disabled-worlds-as-whitelist", boolean, that turns the disabled-worlds list in a whitelist, some servers have a lot of worlds, or add worlds constantly, so having to add each time the worlds to the blacklist is a pain.

**Comment by Drc-DEV** [comment]
Still nothing on this? it's really easy to implement @SirBlobman

**Comment by SirBlobman** [comment]
@Drc-DEV Sorry for no reply, I get distracted easily and I've been super busy

I'll add this option in a future update, my only question is why you would have more than a few worlds, as each one adds more processing for the server and can cause extra lag.

**Comment by Drc-DEV** [comment]
@SirBlobman The new 11.x combatlogx removed this feature, which I once again ask for.
