### ISSUE TITLE
World Guard Expansion Feature - Remove Combat Log Timer Reset

### ISSUE THREAD

**Issue by iavengetheweak** [SirBlobman/CombatLogX#128]
**What minecraft version are you currently using?**
Latest Paper 1.16.1 #111 

**What version of CombatLogX are you using?**
10.0.0.0.Beta-246

**What is your feature request?**
Option to disable the combat tag counter being renewed when a player is inside a World Guard region where PvP is typically disabled.  

Example: 
Two World Guard regions, each accessible through the other zone by walking, are in this scenario:
Warzone - PvP is always enabled
Safezone - PvP is only enabled to those who were in combat in the Warzone and ran into the Safezone

Two players are fighting in a Warzone.  When fighting they are given the 20 second combat tag which renews each time they get hit by the other player.  One player flees to the Safezone.  The two players continue to fight inside the Safezone, but their combat tags do not keep resetting.  So, after being inside the Safezone for 20 seconds they will lose their combat tag, even if the player is repeatedly hit while inside the Safezone.

**Comment by Tomi010817** [comment]
Ooh, this seems more like a bug than a feature request. VULNERABLE is a very handsome feature of CombatLogX. And that behaviour that you told, must be fixed. The timer must be reset every time they hit, even if they are inside of a region without pvp.

**Comment by SirBlobman** [comment]
Added config options for this in the latest commit, a build should be out on Jenkins soon.

**Comment by Tomi010817** [comment]
Works perfect!
