### ISSUE TITLE
[BUG] "disable-scoreboard" glitched. (Notifier/Title-Manager/)

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#129]
Hello! I will post 2 bugs and 5 suggestions that I have for this plugin on the following tickets.

---
**Describe the bug:**
When you set `disable-scoreboard` to `false` (inside of `Title-Manager.yml` from the "Notifier" expansion), it will still disabling it when you get tagged.

**To Reproduce:**
I have the lastest version of Title Manager supported for 1.8.8, I tried the lastest beta of CombatLogX, and everything worked great inside of the Title-Manager options from the Notifier expansion, but `disable-scoreboard` seems to be stuck on `true`, even if you set it to `false`.

**Expected behavior:**
When you set `disable-scoreboard` to `false`, it shouldn't disable your Title Manager scoreboard when you get tagged

**Minecraft Version:**
 - 1.8.8

**CombatLogX Version:**
 - v10.0.0.0.Beta-246

**Comment by SirBlobman** [comment]
Thanks for the bug report!

The `title-manager.yml` file is useless in CombatLogX 10.0.0.0. I will probably remove it soon.

This is because the title manager plugin automatically disables itself when it detects a player in combat
(Since TM 2.2.6)
