### ISSUE TITLE
[BUG] TitleManager - Bypass permission bug.

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#130]
**Describe the bug**
So when you have the permission to bypass combat tags and someone hits you or you tag yourself with the command, the TitleManager scoreboard will still get disabled. Apparently something very wrong is happening with the `disable-scoreboard` setting from Notifier expansion on `Title-Manager.yml`. This last thing written is because `restore-scoreboard` works perfectly fine, the only thing getting really buggy is `disable-scoreboard`.

**To Reproduce**
So you basically give yourself the permission to bypass combat tags, and then you try tagging yourself (you need Notifier expansion). Your Title-Manager scoreboard will dissapear.

**Expected behavior**
When you have permission to bypass combat tags, nothing is supposed to happen to you.

**Minecraft Version**
 - 1.8.8

**CombatLogX Version:**
 - v10.0.0.0.Beta-246

**Comment by SirBlobman** [comment]
Thanks for the bug report!

Title Manager handles its own disabling/enabling of scoreboards since v2.2.6

**Comment by Tomi010817** [comment]
No problem sir!
And you are right, this only happens at the lastest dev-version of this plugin, apparently it was working fine at the version released on Spigot. I already submitted a suggestion to bring compatibility on the lastest build of CombatLogX in the github of TitleManager, you can check it out [**_here_**](https://github.com/Puharesource/TitleManager/issues/290) if you want.
