### ISSUE TITLE
[IDEA] Left and right bars more customizable.

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#131]
**_EDITED_**: On the way of suggesting all the other things after this github, I came up to this one again with a definitive idea for making this bars fully compatible with the suggestion made on #135 , and this because currently you are only able to define one template for the actionbar message, and when cooldown is bigger or different on other people, it will move out from the center, and it can even become visually horrible from large number tag durations. For more info read on "Additional feature request" below.

---
**What minecraft version are you currently using?**
Minecraft 1.8.8

**What version of CombatLogX are you using?**
v10.0.0.0.Beta-246

**What is your feature request?**
I saw that it has been implemented a way to set the color to the bars inside the `actionbar.yml` from Notifier expansion, that's really good since I wanted to change them recently!
These are 2 more things that would make those variables fully customizable for the player preference:
- Be able to change the symbol for {bar_left} and, separately, the symbol for {bar_right} with color codes and multi-character support.
- An option to choose whether you want your timer animation to decrease or increase. So if you set it to increase, the bars animation instead of going from right to left, it will go from left to right. (giving a visual effect that it is getting full instead of getting empty).

[If I wasn't clear, here is an example of the config template of `actionbar.yml` with these features included. (this is just a template idea, you can decide either if you want them different or something else).](https://pastebin.com/qR0qH3SL)

**_Additional feature request:_**
So this additional feature would consist on a system for avoiding extremely large timer durations and timers being moved from center making the actionbar look visually horrible. This will limit the amount of bars that will appear on the actionbar, also with the number amount being changeable to your preference. So I think that this amount should be on a total of 50 bars by default, and there may be another setting to whether you want to enable or disable this feature, and being disabled by default, so if the player wants to test it, then he will just have to enable it to see it working because the default `timer` is 15.
**How would it work?**
It would be pretty mathematical its functionality. Lets make an example:
So the setting telling the total amount of bars is "50" and the default timer is "15" seconds. So if the plugin needs to know how many "bars to fill" each second, then it will do `50/15`, and that is equal to `3.333`. That means that each second, it will "fill up 3 bars" because it will truncate on the current number ignoring their following decimals.
**Strange cases:** It would apply the same if for example, the player has changed his bar-symbols to "|||" for example. On that strange example case, it would "fill up" 3 times that symbol, that is, 9 "bars".
**Another special case:** So I thought of another setting called `actionbar-update-interval`, that it will define how often the actionbar will be updated (in ticks), in case that the speed of a tag timer is pretty fast and you want it to be updated every tick so it looks more fluid, though I don't know if this is a possible thing. It is also added on the following config template.
**How could this look on the config?**
[Here is an extra template including this feature and all previous features on this github, in case you would like to see an example with explanations of how it would look on the `actionbar.yml`](https://pastebin.com/khm9N2KL)

**Comment by SirBlobman** [comment]
Thanks for the feature request! Customizable bar symbols sounds like a good idea that I may work on soon. I can also add a "scale" option so that the server owner can select the exact amount of bars that they want to be displayed.

As for update speed, CombatLogX sends the timer info every 2 ticks (period is `10L`)

I seem to be having some issues accessing your links, do you mind uploading them to another website? Hastebin seems to have deleted them.

**Comment by Tomi010817** [comment]
Hello SirBlobman! I'm really happy you liked my idea. 
Don't know why you can't access the hastebins, anyways, I will repost the links onto Pastebin instead. You should be able to access them now.

And now knowing that update speed is 2 ticks, I guess that you will be able to fix the issue on #139 since I first thought that was caused because of the slow update interval.

**Comment by SirBlobman** [comment]
The custom action bars and scale should be added in the latest Jenkings build 🙂

**Comment by Tomi010817** [comment]
Yess!
It works perfect, thanks a lot @SirBlobman !
Scale feature and symbol for right and left work like a charm.

The last thingy remaining in this huge suggestion would be the setting to make the bars animation go from left to right instead of right to left.

> An option to choose whether you want your timer animation to decrease or increase. So if you set it to increase, the bars animation instead of going from right to left, it will go from left to right. (giving a visual effect that it is getting full instead of getting empty).

**Comment by Tomi010817** [comment]
EDIT: I forgot to mention that there is also remaining a feature to make actionbars update faster than only every second.
If CombatLogX sends the timer info every 2 ticks, I guess it is possible to make this feature since I know plugins to decorate actionbar where you can make animations making the actionbar update every tick. (not update actually, it just sends another actionbar with their changes) 
_I ask for this one because in case you set a scale that is much higher than the actual timer, it would give a visual effect that it reduces faster than usual, but without this feature, you see that it reduces like in frames._
