### ISSUE TITLE
[BUG & SUGGESTION] Notifier toggle command not working.

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#132]
**Describe the bug**
Apparently the toggle command for the Notifier expansion, isn't existing on the lastest build.

**To Reproduce**
You only need to have the Notifier expansion in, and slash `/combatlogx toggle`. It will take it as an unknown command.

**Expected behavior**
To work well I guess, and disable all notifier information that player wants to hide.

**Minecraft Version**
 - 1.8.8

**CombatLogX Version:**
 - v10.0.0.0.Beta-246

**Extra:**
I know this is too much to ask for, but is it any chance there can be a permission (inherited by default) to see notifier information?, so if it gets denied, the player won't see Notifier information. Or the other alternative would be to add `<on/off>` argument on the notifier toggle command, and if <on/off> argument isn't specified, then it will toggle the opposite to the player. `/combatlogx toggle (on/off)`

**Comment by SirBlobman** [comment]
The command format is now `/notifier boss-bar/score-board/action-bar`. I'll keep this issue open so that I don't forget to add the `on/off` options on it

**Comment by Tomi010817** [comment]
I've tested it and it works as it should! Thanks SirBlobman!

Things remaining:
- `on/off` parameter.
- Permission required to run the command
- Maybe a message to display when you run the command? Like "Notifier > You have {enabled/disabled} your {module}" for example.
