### ISSUE TITLE
[IDEA] Anti loot-stealing for the "Newbie Helper" expansion.

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#133]
**What minecraft version are you currently using?**
Minecraft 1.8.8

**What version of CombatLogX are you using?**
v10.0.0.0.Beta-246

**What is your feature request?**
I doubt that this will be possible, but if it is, then I guess that Newbie Helper would become the perfect solution for its topic (including the next suggestion as a "top" for it). 
The idea consists in a new system for the expansion, that will **log** all the items that a player drops from death (only when killed by another player) for a timelapse of 30 seconds. On that timelapse, those logged items won't be allowed to be picked up by any player that has protection status from this expansion, displaying them a configurable message that tells them that they can't steal loots from other players when they have Newbie Protection status, also with a message-cooldown similar to the one on `cheat-prevention.yml` so it doesn't spam.
This idea will prevent players with Newbie protection, from stealing loots of other players unfairly.

**Comment by Olivoz** [comment]
Added in v11 beta builds
