### ISSUE TITLE
[IDEA] "/pvptoggle" Command more manipulable.

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#134]
**What minecraft version are you currently using?**
Minecraft 1.8.8

**What version of CombatLogX are you using?**
v10.0.0.0.Beta-246

**What is your feature request?**
I have two ideas to make the `/pvptoggle` command much manipulable for everyone:
- First one would be to add another **optional** argument to the command, so you can specify if you want it to turn on, or off. The command would turn into: `/pvptoggle (on/off)`
- The second one would be a permission required to run this command, like `combatlogx.pvptoggle` (for example).

**Comment by SirBlobman** [comment]
Added in V11, you can check beta builds on the CodeMC Jenkins site.
