### ISSUE TITLE
[IDEA] Permission based Tag Timers

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#135]
**What minecraft version are you currently using?**
Minecraft 1.8.8

**What version of CombatLogX are you using?**
v10.0.0.0.Beta-246

**What is your feature request?**
This last idea would consist of a permission based tag timers, so with that feature, you will be able to either give your donor ranks a better and lower duration for when they get tagged, or even make an upgrade shop for personally lowering your tag duration.
**How can this work?**
There can be a new setting at the general `config.yml` (for ex. called "tags-mode") so it is set to "DEFAULT" by default, but if you set it to "PERMISSION_BASED" it will turn it into this new mechanic idea. This mechanic would check if the player has the permission `combatlogx.timer.X` and "X" being a random number you choose, and that number will be taken as the timer duration on combat tags for the player or group whom the permission was given to. _The lowest numbers on permissions inherited will **override**_, and if the player doesn't have any permission of these, then the default `timer` set on the config, will be used. And if you want to give someone a timer duration **longer** than the default `timer` set on the config, then you will have to deny the permission `combatlogx.timer.X` to the player and "X" being the default `timer` set on the config and once you do that you can freely give that player the permission with the longer duration you want.

**Comment by SirBlobman** [comment]
Added this feature in v11, check the Jenkins if you would like to test the beta builds for it.

**Comment by Tomi010817** [comment]
Thanks a lot @SirBlobman !
