### ISSUE TITLE
[IDEA] New behavior for "on-enemy-death"

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#136]
**What minecraft version are you currently using?**
Minecraft 1.8.8

**What version of CombatLogX are you using?**
v10.0.0.0.Beta-246

**What is your feature request?**
Currently, when you set to `true` the setting `on-enemy-death` inside the `config.yml`, everytime you hit a new player, the combat tag will reset and not only the timer, also the target who is tagging you will be renewed, forgetting about the previous one. So because of this behavior, you can easily bypass combat tags by killing players with nothing equiped, so you will bypass your combat tag and be able to quit before the previous opponent tags you again. So this github is an idea that I had to help you become this option a definitive feature for the plugin without any problems on its behavior.
_**"A combat tag for each target":**_
So basically, on this new behavior idea, when you attack or get attacked by another player when you are already in combat tag, your timer will be renewed and the target of that timer will become that new player _**but**_, the previous **timer** and previous **target player** won't be forgotten, so unless the timer of that previous combat tag ends, you will have to get rid of both targets in order to skip your combat tag. It will work respectively in case you have more than 2 combat tags (one timer for each opponent) cumulated.
**Additional information to have it clear:** The timer to display, will always be the more recent tag, or in other words, the last player that attacked you (or that you attacked).
In case that you are in a combat with 2 opponents, and the target who last attacked you dies first, the timer of the other opponent will display, replacing your more recent timer. Also the message of "your enemy died" will only display once you get fully rid of your combat tag with all your opponents, and it can be replaced to something like "You won the fight and you are no longer in combat." so that would avoid future "missmatches" with plural cases.

**Comment by SirBlobman** [comment]
@Tomi010817 Not sure if you still use this plugin, but here is a version to test:

https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX-Multiple-Enemies/1/

**Comment by Tomi010817** [comment]
Hi @SirBlobman 
Indeed I don't even manage servers anymore, and rarely play the game. Anyways, I can test it if you still need me for it. Thank you for adding this new behavior, pretty sure it is gonna be helpful to many people that uses this plugin.
