### ISSUE TITLE
[SUGGESTION] Eggs, Snow_balls and enderpearls

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#137]
**What minecraft version are you currently using?**
Minecraft 1.8.8

**What version of CombatLogX are you using?**
v10.0.0.0.Beta-246

**What is your feature request?**
As far as I know there is no current way to specifically decide whether you want, for instance, to make only arrows able to engage players in combat tag, but not snow balls, eggs or enderpearls. It would be very good to have sub-settings inside the `link-proyectiles` option from `config.yml`, where you can decide if you want specific proyectiles to be disabled.

**Comment by SirBlobman** [comment]
Thanks for the suggestion, I'll add this to the next version :)
