### ISSUE TITLE
[SUGGESTION] New permission, bypass for blocked-cmds.

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#138]
**What minecraft version are you currently using?**
Minecraft 1.8.8

**What version of CombatLogX are you using?**
v10.0.0.0.Beta-246

**What is your feature request?**
 It would be also a good thing to have a permission to bypass the blocked commands set inside `blocked-commands` from the "Cheat-Prevention" Expansion. This would allow to give certain player or group, permission to do any command though they will still be able to get tagged in combats. Maybe "`combatlogx.blockedcmds.bypass`"?

**Comment by SirBlobman** [comment]
Thanks for the suggestion, if I do add this the permission will most likely be `combatlogx.bypass.cheat.prevention.commands`
