### ISSUE TITLE
Bug PlayerPreTagEvent

### ISSUE THREAD

**Issue by angelcraft** [SirBlobman/CombatLogX#142]
**Describe the bug**
When i try to punch a mob or i throw myself into a cactus i dont get tagged.

**To Reproduce**

>.... [08:03:55 INFO]: [CombatLogX] [Debug] Detected EntityDamageByEntityEvent...
>.... [08:03:55 INFO]: [CombatLogX] [Debug] Damaged entity is not a player.
>.... [08:03:55 INFO]: [CombatLogX] [Debug] The PlayerPreTagEvent was cancelled.

**Expected behavior**
A actionbar tag

**Minecraft Version**
1.16.1

**CombatLogX Version:**
Latest 10.0.0.0-Beta #252

**Additional context**
Everything is ok but the problem is this, i tried to erase all of my files and start again but didnt work

**Comment by Olivoz** [comment]
Please provide the full output from /clx version. We're also going to need your DamageTagger config

**Comment by Olivoz** [comment]
This can be closed. Solved by updating Paper
