### ISSUE TITLE
[BUG] Could not pass event PlayerCombatTimerChangeEvent

### ISSUE THREAD

**Issue by Ant4rez** [SirBlobman/CombatLogX#144]
**Describe the bug**
The console gets spammed infinitely with this message: https://hastebin.com/negefoluqi.sql

**To Reproduce**
I don't exactly i just looked at the console in a random moment and i see this message constantly spammed.

**Expected behavior**
Nothing.

**Minecraft Version**
Server Version: git-Purpur-706 (MC: 1.16.1)
Bukkit Version: 1.16.1-R0.1-SNAPSHOT
NMS Version: 1_16_R1
Minecraft Version: 1.16.1

**CombatLogX Version:**
CombatLogX by SirBlobman

Latest Version: v9.9.4.0
Installed Version: v10.0.0.0.Beta-262

**Additional Info;**
Plugins (69): AdvancedAchievements, AdvancedHelp, AdvancedPortals, AngelChest, AuctionMaster, AuthMe, BeehivesPro, BetterEnd, BKCommonLib, BossLand, BossShopPro, ChestSort, Chunky, Citizens, CombatLogX, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftEnhance, DragonSlayer, Drop2Inventory, DuoAuth*, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, FastLeafDecay, FastLogin, FogusCore, GoldenEnchants, Harbor, HeadsPlus, Holograms, IllegalStack, Jobs, Kyra, LevelledMobs, LimitPillagers, LoreAttributesRecoded, LuckPerms, LWC, LWCTrust, mcMMO, MeteoritesPro, Minepacks, MoarBows, My_Worlds, NoCheatPlus, Parkour, PhantomLib, PL-Hide, ProtectionStones, ProtocolLib, SAML, ServerListPlus, SimplePets, SkinsRestorer, spark, SpigotLib, TAB, Thirst, Vault, VillagerOptimiser, VoidGenerator, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, XProtect*

**Comment by Olivoz** [comment]
We're going to need the full output from /clx version. (The expansion versions too). The error seems to be caused by the Notifier expansion. Please try to reset the file and see if that fixes your error

**Comment by Ant4rez** [comment]
Cheat Prevention v15.2
Citizens Compatibility v15.2
WorldGuard Compatibility v15.1
Logger v15.1
Newbie Helper v15.1
Notifier v15.3

**Comment by Olivoz** [comment]
Alright thanks for the information. I want to let you know that a second report of this issue came in a while ago. I've been able to track the issue to an outdated or invalid jar. Try to delete your notifier expansion jar with a fresh one.
