### ISSUE TITLE
Unable to resolve as dependency

### ISSUE THREAD

**Issue by PikaMug** [SirBlobman/CombatLogX#147]
**Describe the bug**
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.908 s
[INFO] Finished at: 2020-08-19T00:46:23-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gravitytubes: Could not resolve dependencies for project com.benzoft:gravitytubes:jar:1.10.5: Failed to collect dependencies at com.SirBlobman.combatlogx:CombatLogX-API:jar:10.0.0.0-SNAPSHOT: Failed to read artifact descriptor for com.SirBlobman.combatlogx:CombatLogX-API:jar:10.0.0.0-SNAPSHOT: Could not find artifact com.SirBlobman.combatlogx:CombatLogX-parent:pom:10.0.0.0-SNAPSHOT in codemc-repo (https://repo.codemc.io/repository/maven-public/) -> [Help 1]
```

**To Reproduce**
Clone a repository that uses CombatLogX as a dependency, namely https://github.com/Benz56/GravityTubes and attempt to compile with `mvn clean install`

**Expected behavior**
Build success

**Screenshots**
N/A

**Minecraft Version**
N/A

**CombatLogX Version:**
10.0.0.0

**Additional context**
Nexus repository manager reports that the version tag should be 10.0.0.0-20200815.163735-76 but that does not yield success either https://repo.codemc.io/#browse/browse:maven-public:com%2FSirBlobman%2Fcombatlogx%2FCombatLogX-API%2F10.0.0.0-SNAPSHOT%2F10.0.0.0-20200815.201325-80

**Comment by Olivoz** [comment]
This project is a mess. It has multiple compile issues such as invalid compile version and missing dependencies. I'm not going to take the effort to clean up and fix that project. Instead I tested with my own project and the reop works perfectly fine.

**Comment by PikaMug** [comment]
Even after addressing those issues, the same cause for build failure occurs. I've opted to use [Jitpack](https://jitpack.io/#SirBlobman/CombatLogX) for the time being.
