### ISSUE TITLE
TownBlock Permission check for SafeArea detection

### ISSUE THREAD

**Issue by Kovalskki** [SirBlobman/CombatLogX#148]
My players found this error while trying to make arena. 
If you try to pvp inside a towny plot, you get stuck. 
Because the plugin does not control plot permissions.

Version: CombatLogX-10.0.0.0.Beta-267
Towny Version: 0.96.2.0
Minecraft Version: 1.16.1

**Comment by Olivoz** [comment]
Thanks for bringing this issue to our attention :) I've seen your fork and we'll implement the fix as soon as possible

**Comment by Kovalskki** [comment]
Fixes #149

**Comment by Kovalskki** [comment]
Fixed #149
