### ISSUE TITLE
TownyCompability UnderAttack check for SafeZone detection

### ISSUE THREAD

**Issue by Kovalskki** [SirBlobman/CombatLogX#151]
Towny flagwar event does not turn on pvp. Required extra check.

Version: CombatLogX-10.0.0.0.Beta-267
Towny Version: 0.96.2.0
Minecraft Version: 1.16.1

**Comment by Kovalskki** [comment]
#150

**Comment by SirBlobman** [comment]
Closed by merging pull request #150
