### ISSUE TITLE
Players Can Fall Through Blocks

### ISSUE THREAD

**Issue by RFSMassacre** [SirBlobman/CombatLogX#153]
**Describe the bug**
When in combat, people can break the block beneath them and even though the event is cancelled, players can fall through the block.

**To Reproduce**
Get yourself in combat, then stand on a block and attempt to break it underneath you. Even though the event is canceled, players can fall through it.

**Expected behavior**
The canceled event should prevent people from moving through them.

[
![image](https://user-images.githubusercontent.com/5137851/92416427-6d6d7880-f12b-11ea-82a1-966930215f42.png)
](url)

**Additional context**
I admit I am using Tuinity (Apollo16) for more optimization but I don't believe that it should affect blocks to do that while in combat. No other combat tag plugins do this.

**Comment by SirBlobman** [comment]
Sorry for the late response, I'll try to fix this soon. Does the issue still occur if you remove the following expansions?
- GriefPrevention Compatibility
- WorldGuard Compatibility

**Comment by RFSMassacre** [comment]
I removed both and the issue went away. I then readded WorldGuard and the problem hasn't returned. I assume it's something to do with the GriefPrevention expansion.
