### ISSUE TITLE
An thing about the command /pvp

### ISSUE THREAD

**Issue by Remski01** [SirBlobman/CombatLogX#154]
**Describe the bug**
The command `/pvp` isnt or doesnt get registered causing it be red when used.

**To Reproduce**
Type it in...

**Expected behavior**
That it shows it as command.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Minecraft Version**
 - >.... [19:36:06 INFO]: Server Version: git-Paper-135 (MC: 1.16.1)

**CombatLogX Version:**
>.... [19:36:06 INFO]: Installed Version: v10.0.0.0.Beta-287

**Additional context**
...

**Comment by SirBlobman** [comment]
Duplicate with #155
