### ISSUE TITLE
[Request] A new placeholder pretty please.

### ISSUE THREAD

**Issue by Remski01** [SirBlobman/CombatLogX#156]
**What minecraft version are you currently using?**
.... [19:36:06 INFO]: Server Version: git-Paper-135 (MC: 1.16.1)

**What version of CombatLogX are you using?**
.... [19:36:06 INFO]: Installed Version: v10.0.0.0.Beta-287

**What is your feature request?**
An placeholder for when you have pvp toggled on. Something like `%combatlogx_pvp_status%` what would return an value set in the `en_US.yml` file. So we can use it on the TAB so its much more clear who have it enabled and who not.

**NOTE:**
`combatlogx_status` isnt what i talk about because that shows when an player is in combat modus or not.

**Comment by SirBlobman** [comment]
Thanks for the suggestion, I will add it in the next update :)

**Comment by Remski01** [comment]
Thanks!

**Comment by Baterka** [comment]
This would be awesome :) I can add it in fork and do pull req :)

**Comment by SirBlobman** [comment]
Added in V11, you can check beta builds on the CodeMC Jenkins site.
