### ISSUE TITLE
Actionbars, bossbars don't work. NMS not found spamming users chat instead!

### ISSUE THREAD

**Issue by cloakfox** [SirBlobman/CombatLogX#157]
**Describe the bug**
They just dont work, using default notifier configs aswell. (I saw a previous bug report with a reply that mentioned it's wise to update configs etc, so I let everything regen again)
**To Reproduce**
Install latest combatlogx on 1.16.1 paper server with notifier expansion

**Expected behavior**
To have them work...

**Screenshots**
https://pastebin.com/LMapyYLF

**Minecraft Version**
1.16.1

[09:28:44 INFO]: This server is running Tuinity version git-Tuinity-"650532a" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[09:28:44 INFO]: Checking version, please wait...
[09:28:44 INFO]: Previous version: git-Tuinity-"d3dc35c" (MC: 1.16.1)
[09:28:44 INFO]: Unknown version

**CombatLogX Version:**
9.9.4.0

**Additional context**

**Comment by SirBlobman** [comment]
![Screen Shot 2020-09-10 at 10 03 19 AM](https://user-images.githubusercontent.com/9003290/92741806-00392d80-f34d-11ea-9a6a-76b6a58de677.png)

The beta version is 10.0.0.0-Beta<number>, not 9.9.4.0

**Comment by cloakfox** [comment]
I use 1.16.1 not 1.16.2 but ok
