### ISSUE TITLE
Missing expansions?

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#158]
**Describe the bug**
CLX-11.0.0.0-Beta-305 seems to be missing many of the former expansions:
- Citizens Compatibility.jar
- Notifier.jar
- PlaceholderAPI Compatibility.jar
- Residence Compatibility.jar
- SkyBlock Compatibility.jar
- WorldGuard Compatibility.jar

It does contain new expansions:
- Action Bar.jar
- Glowing.jar
- Scoreboard.jar

**To Reproduce**
Unzip CombatLogX-11.0.0.0-Beta-305.zip
Look at the contents

**Comment by SirBlobman** [comment]
Thanks for the concern, but 11.0.0.0 is still in the process of being made. All these expansions will be back and some of them will be changed (e.g. Notifier will turn into separate expansions, such as "Glowing", "Action Bar", and "Boss Bar"). I'll keep this issue open until I'm able to finish all of the expansions.

**Comment by SlimeDog** [comment]
Thanks. As you know, I tend to test dev builds as they drop. No worries.

**Comment by SirBlobman** [comment]
No problem, thanks for testing it so early :)

**Comment by SirBlobman** [comment]
Slowly adding/completing more expansions, the major ones should already be completed. I'll close this when all of them are 100% finished.

**Comment by SlimeDog** [comment]
Thanks. I've been following along. Still running 10.3.8.3 on my servers.

**Comment by SlimeDog** [comment]
It looks like most of the expansions exist in 11.0.0.0-b373. Still missing:
- Residence

**Comment by SirBlobman** [comment]
Thanks. The CodeMC version doesn't have the latest commits btw. Here is a link to my new Jenkins:
https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/

**Comment by SlimeDog** [comment]
Thanks. My update-checker is linked to there, now.

**Comment by SirBlobman** [comment]
All planned expansions for V11 are now available for testing, I'm going to close this now 🙂

**Comment by SlimeDog** [comment]
Confirmed. I see them all (that we use, and lots of others). Thanks.
