### ISSUE TITLE
Add an option to allow chat while in combat

### ISSUE THREAD

**Issue by TreemanKing** [SirBlobman/CombatLogX#161]
**What minecraft version are you currently using?**
1.16.2
**What version of CombatLogX are you using?**
Most recent
**What is your feature request?**
Add an option in configuration to allow players to talk whilst in combat

**Comment by Olivoz** [comment]
Most recent isn't a version. Send the output from /clx version. Also this is already possible in the CheatPrevention config. It's recommended that you take a look through the documentation and/or ask us on discord.
