### ISSUE TITLE
[BUG|FactionsUUID] Faction members can hit between them, when in combat tag. 

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#162]
**Describe the bug**
When someone enters in combat tag on any circumstance, other players that are from his faction, will be able to hit him during his combat tag.

**To Reproduce**
In my case, to reproduce it, I were with 2 friends. One was of my faction, and the other one, was factionless. Whenever my friend entered in combat tag with the factionless guy, I was able to hit him.
I used FactionsUUID for the faction's system.

**Expected behavior**
CombatLogX should not affect on any circumstance, the PvP between players from the same faction.

**Minecraft and CombatLogX Version**
 - https://i.imgur.com/7NrImkb.png

**Additional context**
I already tried uninstalling the Factions compatibility expansion, but that didn't fix it.

**Comment by SirBlobman** [comment]
@Tomi010817 Do you mind trying this in V11 and telling me if it is still an issue? You can find the beta builds on the CodeMC Jenkings page.

**Comment by Tomi010817** [comment]
@SirBlobman Hi!
I'm using v10.3.8.0 and apparently the bug is not happening, I think this is already fixed.
