### ISSUE TITLE
Fly not getting totally disabled + Suggestion for "cheat-prevention"

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#167]
**Describe the bug**
When you have fly status activated, and you enter in combat without actually flying, you can still kind of "fly" by pressing space repeatedly.

**To Reproduce**
Just activate your fly status with "/fly", then enter in combat without flying. Once you enter in combat, press the space button repeteadly and you can fly.

**Expected behavior**
To disable the fly status completely when you enter in combat.

**CombatLogX Version:**
 - https://i.imgur.com/DOP1M8D.png

**Extra suggestion:**
This suggestion would consist of removing the "StartWith" on the blocked and allowed commands from cheat-prevention expansion, so if you set "*" as blocked commands, and then you add "/t" as allowed command, players would be able to use that command with their sub arguments, but they won't be able to do things such as "/tpaccept" thanks to the StartWith of "/t" (currently they can). This is pretty problematic actually, and it should be modified as how it is right now.

**Comment by djeroon** [comment]
I'm also waiting for this fix.

**Comment by nickdroppert39** [comment]
Same here, when is it gonna get fixed?

**Comment by SirBlobman** [comment]
This issue will be fixed soon, in the future make a separate issue if you have a bug report and a feature request so I can keep track of them separately.

**Comment by Tomi010817** [comment]
No worries I will separate them, and thanks for the fix!
