### ISSUE TITLE
Disable combatlog on hitting mobs

### ISSUE THREAD

**Issue by cSharpTrash** [SirBlobman/CombatLogX#168]
If I hit a mob i enter combat and it just doesnt make sense. Could I make it so that doesn't happen?

**Comment by Olivoz** [comment]
Remove the mob tagger expansion.

**Comment by cSharpTrash** [comment]
Thank you, How do i remove the
"Good job! You killed an BLAZE,"


Den ons 23 dec. 2020 kl 23:26 skrev Olivo <notifications@github.com>:

**Comment by Olivoz** [comment]
That's from the rewards expansion. I recommend you join our discord instead of asking here. You'll get faster responses there :)
