### ISSUE TITLE
Option on Vanish expansion to not tag others

### ISSUE THREAD

**Issue by Tomi010817** [SirBlobman/CombatLogX#170]
**What minecraft version are you currently using?**
Paper 1.8.8

**What version of CombatLogX are you using?**
10.3.8.0

**What is your feature request?**
An option in the CompatVanish folder to prevent vanish players from tagging **others** when hitting them.

**Comment by SirBlobman** [comment]
This has been added in the V11 beta builds

**Comment by Tomi010817** [comment]
Thank you!
