### ISSUE TITLE
Permissions list

### ISSUE THREAD

**Issue by RabbitXOne** [SirBlobman/CombatLogX#174]
I can't find the permission list for this plugin anywhere. Could someone send a link to them?

**Comment by Golvore** [comment]
combatlogx.bypass

**Comment by RabbitXOne** [comment]
There is only one permission?
On my server, I would like players to be able to enter the command /pvp, but it shows that they cannot access it.

**Comment by Olivoz** [comment]
The permissions are:
- combatlogx.command.combatlogx.help
- combatlogx.command.combatlogx.reload
- combatlogx.command.combatlogx.tag
- combatlogx.command.combatlogx.untag
- combatlogx.command.combatlogx.version
The bypass permission can be configured in the config but is combatlogx.bypass by default.
I recommend you join our discord for simple questions such as this :)

**Comment by RabbitXOne** [comment]
Okay, thank you =)
