### ISSUE TITLE
Command blocker is case sensitive

### ISSUE THREAD

**Issue by MedicOP** [SirBlobman/CombatLogX#177]
CheatPrevention's Command blocker is case sensitive, meaning anyone can easily bypass it by just uppercasing any part of the command.

Example: /hOme instead of /home

This was fixed before in #91 but was broken again in https://github.com/SirBlobman/CombatLogX/commit/dfce4b9fe69fa9118f9d06221c312a93f1e2ad36

**Comment by SirBlobman** [comment]
Should be fixed in V11
