### ISSUE TITLE
Fishing Rod Bug

### ISSUE THREAD

**Issue by Danielpeter-99** [SirBlobman/CombatLogX#181]
Players can use a fishing rod (no matter if inside a claim or worldguard region) to push players around to a PvP zone

**To Reproduce**
"Fish" a player and it will knockback

**Expected behavior**
Action being completely canceled where PvP is found off

**Screenshots**
https://streamable.com/h69fbk

**Minecraft Version**
https://i.imgur.com/IvqMnWB.png

**CombatLogX Version:**
https://i.imgur.com/IvqMnWB.png

**Comment by Olivoz** [comment]
This is not caused by CombatLogX

**Comment by Danielpeter-99** [comment]
> This is not caused by CombatLogX

Shouldn't the damage and knockback be blocked by combatlogx in areas with no PvP?

**Comment by Olivoz** [comment]
> > This is not caused by CombatLogX
> 
> Shouldn't the damage and knockback be blocked by combatlogx in areas with no PvP?

CombatLogX is not a region protection plugin. Why would we prevent it

**Comment by SirBlobman** [comment]
Fishing rods will now tag players if the config option is enabled, PVP detection is up to your region plugin though 

Reference Commit: d61ffc11c2717eeafb7510b2f26303eb7f88c1a4
