### ISSUE TITLE
Add Blacklist

### ISSUE THREAD

**Issue by SirDeathnote1** [SirBlobman/CombatLogX#186]
i want to find how to backlist for

 when they in Combat tag that they go to straight /spawn or home in Tag 

However if they not tag , they can go back to /home and /spawn

**Comment by Olivoz** [comment]
Install and configure the CheatPrevention to block commands during combat

**Comment by SirDeathnote1** [comment]
is this one https://gyazo.com/c19e6196c2615691ae4512d8d2f7d566

**Comment by Olivoz** [comment]
No. CheatPrevention is an expansion. When installed it will create it's own config file. I recommend you join our discord for faster replies :)

**Comment by Olivoz** [comment]
Solved in discord DMs
