### ISSUE TITLE
Exception onEnable

### ISSUE THREAD

**Issue by Drc-DEV** [SirBlobman/CombatLogX#189]
**Describe the bug**
Plugin does not load properly due to exception.
https://pastebin.com/PzdTv8Gk

**Minecraft Version**
1.16.4 Paper

**CombatLogX Version:**
CombatLogX-11.0.0.0-Beta-404

**Comment by Olivoz** [comment]
You need to install SirBlobmanCore

**Comment by Drc-DEV** [comment]
> You need to install SirBlobmanCore

I had the release version of SBC instead of latest dev build
