### ISSUE TITLE
bossbar are bugging

### ISSUE THREAD

**Issue by MentosPL** [SirBlobman/CombatLogX#19]
it's normal, when i PvE with a few mobs at once.

http://prntscr.com/hjxsgh

**Comment by SirBlobman** [comment]
Any errors in console?

**Comment by MentosPL** [comment]
no errors, if you can add something to clear bossbars every time it's be fine.

**Comment by SirBlobman** [comment]
The boss bars clear every time on my test server
by any chance, are you using /reload?
That is the only thing that I can think of, and I do not support that command

**Comment by MentosPL** [comment]
i never using /reload command C:

**Comment by SirBlobman** [comment]
Any staff members using reload?
I'll look into this more but I can't replicated it yet

**Comment by MentosPL** [comment]
CombatLogX 5.2.2.1
Spigot: 1.12.2
Java: 8
![jaaaaaaaaaaak](https://user-images.githubusercontent.com/32804020/34283630-23e4f14a-e6cd-11e7-8afa-84e40fec6136.png)

**Comment by SirBlobman** [comment]
Is this an offline-mode server?

**Comment by SirBlobman** [comment]
No response, re-open issue if its still occuring
