### ISSUE TITLE
False Positive Message

### ISSUE THREAD

**Issue by KolakZ** [SirBlobman/CombatLogX#190]
**Describe the bug**
When a player gets combat tagged and killed by a zombie, it says <username> instantly died due to logging out during combat even though they didn't even log out.

**To Reproduce**
You can get combat tagged and have a mob kill you.

**Expected behavior**
I do not want this misleading message to be broadcasted when a player gets combat tagged and doesn't even log out.

**Screenshots**
N/A

**Minecraft Version**
 - 1.16.5

**CombatLogX Version:**
 - v10.3.8.3

**Additional context**
N/A

**Comment by SirBlobman** [comment]
Please send the full output of the `/combatlogx version` command and all your configuration files.

**Comment by KolakZ** [comment]
![image](https://user-images.githubusercontent.com/79867267/115977626-615dec00-a53f-11eb-97d8-0325ec6fbb01.png)

**Comment by KolakZ** [comment]
https://pastebin.com/wE0JAEsk

**Comment by KolakZ** [comment]
https://pastebin.com/5UxL8jxG

**Comment by KolakZ** [comment]
Here is the config and language

**Comment by KolakZ** [comment]
I do not have any expansions

**Comment by Olivoz** [comment]
Could you send your plugin list?

**Comment by KolakZ** [comment]
![image](https://user-images.githubusercontent.com/79867267/116001134-ae31d900-a5b8-11eb-847f-5d7a386093e9.png)
