### ISSUE TITLE
How do i Enable the cheat preventions feature.

### ISSUE THREAD

**Issue by amirshah2935** [SirBlobman/CombatLogX#195]
Hi Sorry to intertupt you on this minor cases..im trying to use ur plugin in my minehut server..after install it seems like working but people seems to be able to fly ..which i can se the features in the wiki is to disable it while combat. how do i enable it, since i check the config file is nothing to do with any cheat prevention or expansion..also under expansion file is empty.
![image](https://user-images.githubusercontent.com/38003845/120636692-80399180-c4a0-11eb-8f48-02cf838c4987.png) if posible would like to know if i can also enable other feature like action bar timer..or others

**Comment by Olivoz** [comment]
You need to put the CheatPrevention jar inside of the expansions folder. You can find it in the zip file that comes with the main plugin. (Go to spigotmc and get it)

**Comment by amirshah2935** [comment]
hi thanks for your promp reply , im not sure if you know this, for the Minehut server, we are not able to upload.jar files. available format that can be upload is as below:

**Comment by Olivoz** [comment]
There is nothing we can do. Please contact Minehut on how to install expansions or pay for a better host.

**Comment by amirshah2935** [comment]
alrighty then..thanks..it seem slike it the server issue then.
