### ISSUE TITLE
DeluxeMenus bug.

### ISSUE THREAD

**Issue by ccegeadamcc** [SirBlobman/CombatLogX#2]
Hi, i blocked warp command from config. But they can still use commands from DeluxeMenus i think this bug appears on Chest Commands too. So pls fix that. And i love your plugin so keep doing that :D

**Comment by SirBlobman** [comment]
DeluxeMenus and ChestCommands have a bypass for bukkits command event system.
Unfortunately, this means I cannot block commands from their chests/GUIs
