### ISSUE TITLE
Console spam/server lag

### ISSUE THREAD

**Issue by Bartek200219** [SirBlobman/CombatLogX#215]
**Describe the bug**
Spam in console and lag server
**To Reproduce**
How can I see the issue for myself? Please explain how it happened.
I tried to reload config but it didnt worked and after 2 minutes my server got huge lag. I looked in console and this plugin started printing errors over and over again. Now my latest.log weight above 2GB 
**Expected behavior**
Disable itself on error like this
**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
https://paste.ee/p/bq2sX
![image](https://user-images.githubusercontent.com/37016424/123809000-84b36780-d8f1-11eb-9271-4e2e0d99234d.png)

**Minecraft Version**
 - Do `/clx version` to find out
1.17
**CombatLogX Version:**
 - Do `/clx version` to find out
newest i guess
**Additional context**
Add any other information about the problem here.

**Comment by TechnicallyCoded** [comment]
From the logs it looks as though the plugin is trying to load the configuration file over and over again due to it being malformed (aka you broke the formatting of the file when editing it)
1. The plugin should probs not kill the server if the config is invalid but instead disable itself
2. Please send your cheat-prevention.yml configuration file

**Comment by Bartek200219** [comment]
https://paste.ee/p/BlhCK
I don't know why it does that, but I commented list of  blocked-potion-list and uncommented line that makes it disable.
I didn't change message-cooldown and I don't see more of config in log.

**Comment by TechnicallyCoded** [comment]
![image](https://user-images.githubusercontent.com/29813490/123833150-5a1fd980-d906-11eb-8eb7-c5c7fbd1b193.png)
As expected you have an extra space here.
When un-commenting, you have to remove the # symbol and the space

**Comment by Bartek200219** [comment]
Thank you, now my config works.

**Comment by Bartek200219** [comment]
I think it shouldn't be closed because:

> 1. The plugin should probs not kill the server if the config is invalid but instead disable itself.. which is probably something that needs fixing ^^

**Comment by TechnicallyCoded** [comment]
I am pretty sure that this applies though
> I am not part of the staff team but I am pretty sure that all updates are done for v10 and v11 is the only version receiving changes.

**Comment by SirBlobman** [comment]
@Bartek200219 Can you please check if this is still an issue with V10.4.1.1 that was released today?
