### ISSUE TITLE
"VULNERABLE" option for the Towny expansion's no-entry-mode is not functioning 

### ISSUE THREAD

**Issue by galacticwarrior9** [SirBlobman/CombatLogX#219]
**Describe the bug**
When the option `no-entry-mode` is set to "VULNERABLE" in the Towny expansion's `config.yml`, combat-tagged players are not able to be damaged if they move into townblocks where PvP is disabled.

**To Reproduce**
1. Download [Towny 0.97.0.9](https://github.com/TownyAdvanced/Towny/releases/tag/0.97.0.9).
2. Create a town (`/t new <town name>`). Ensure PvP is disabled (`/t toggle pvp`).
3. Download the Towny expansion for CombatLogX, and set `no-entry-mode` in its configuration to "VULNERABLE".
4. Combat tag another player.
5. While combat-tagged, move into the town's claim. 
6. Attempt to hit each other inside the claim. No damage will be inflicted.

**Expected behavior**
CombatLogX should override Towny's PvP protection here and allow the combat-tagged players to damage each other.

**Screenshots**
N/A

**Minecraft Version**
 - 1.17

**CombatLogX Version:**
 - 11.0.0.0-Beta-534

**Additional context**
N/A

**Comment by SirBlobman** [comment]
Thanks for the report, I'll fix and test this soon. Keep an eye on the Jenkins change log found here:
[Change Log](https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/changes)
