### ISSUE TITLE
CombatLogX not working

### ISSUE THREAD

**Issue by swinga111** [SirBlobman/CombatLogX#221]
The plugin is uploaded and ready to work but if i hit the player i dont get in combat.

**Comment by Olivoz** [comment]
Did you forget to install SirBlobmanCore. If not please provide server logs

**Comment by swinga111** [comment]
Oh I actually forgot it and didn’t know that I have to install it. Thank
very much and have a nice day!

Olivo ***@***.***> schrieb am Sa. 10. Juli 2021 um 13:38:
