### ISSUE TITLE
Just a bug

### ISSUE THREAD

**Issue by RainOfPain125** [SirBlobman/CombatLogX#23]
In our spawn (which is a faction SafeZone) we have invisable entities (or holograms, whatever you call them) that show text and stuff. When an OP hits them, the combatlogx plugin kicks in and tries to throw the OP out of the SZ (which fails) which just makes the OP shake around back and forth

Also, when an OP hits someone (in the above mentioned scenario inside the SZ) the OP and the player will shake back and forth the same way, except the player is usually kicked for flying or dies.

It would be cool if the factions compatibility "expansion" would stop these kinds of things from happening.

**Comment by SirBlobman** [comment]
Which plugin adds the hologram entities? If it is possible I can add something that will prevent this from happening.

**Comment by RainOfPain125** [comment]
We were using invisible armor stands to project text. Now we're using a holograph plugin and it doesn't seem to be happening. This still however of course happens when an OP (which has perms to hit players wherever they are) hits a player in the SZ

**Comment by SirBlobman** [comment]
Give OPs the bypass perm for CLX
