### ISSUE TITLE
Allow entry to portal only if out of combat 

### ISSUE THREAD

**Issue by thiagogebrim13** [SirBlobman/CombatLogX#238]
**What minecraft version are you currently using?**
1.17.1

**What version of CombatLogX are you using?**
10.4.2.1

**What is your feature request?**
Allow entry to portal only if out of combat

**Comment by SirBlobman** [comment]
'the new release' is not a valid version, please type `clx version` in your console and post the output here.

**Comment by thiagogebrim13** [comment]
> 'the new release' is not a valid version, please type `clx version` in your console and post the output here.

10.4.2.1

**Comment by SirBlobman** [comment]
Thanks, new features will most likely be added in V11, I will mention this request when I've uploaded code that adds the features.

**Comment by thiagogebrim13** [comment]
Okay, this update already has the jenkins version?

**Comment by SirBlobman** [comment]
> Okay, this update already has the jenkins version?

V10 is the Spigot release, V11 is the beta with new features and options. I have not made this feature yet, I will add it in a future V11 beta update.

**Comment by thiagogebrim13** [comment]
A oks, very thanks
