### ISSUE TITLE
No longer loads after Spigot update.

### ISSUE THREAD

**Issue by krusic22** [SirBlobman/CombatLogX#24]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/20971610daa5cbe1685ac9ba0fa93525e7158048
Broke the plugin.

**Comment by SirBlobman** [comment]
Thanks for reporting this, I wouldn't have known without it.
Can you explain to me how a manifest is useful in a plugin?

**Comment by SirBlobman** [comment]
Fixed in 5.2.2.2 by adding a META-INF folder and MANIFEST.MF file
