### ISSUE TITLE
Could not pass event PlayerMoveEvent to CombatLogX v10.4.2.2

### ISSUE THREAD

**Issue by ElMoha943** [SirBlobman/CombatLogX#248]
**Describe the bug**
The console spam this error

**To Reproduce**
Start the server with lastest version.

**Screenshots**
![image](https://user-images.githubusercontent.com/25410859/127786127-40653786-c02d-4f31-914d-3de548d55751.png)

Server Version: git-Tuinity-"9f3435b" (MC: 1.16.5)
Bukkit Version: 1.16.5-R0.1-SNAPSHOT
Minecraft Version: 1.16.5
NMS Version: 1_16_R3

Installed Version: v10.4.2.2

Cheat Prevention v15.3
PlaceholderAPI Compatibility v15.1
Towny Compatibility v15.2
WorldGuard Compatibility v15.3
Newbie Helper v15.4
Notifier v15.12

**Comment by SirBlobman** [comment]
Thanks for the report, do you mind testing if this issue is fixed in the following version?

[10.4.2.4-Dev](https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX-Legacy/lastSuccessfulBuild/artifact/builder/build/CombatLogX-10.4.2.4-Dev.zip)

**Comment by SirBlobman** [comment]
@ElMoha943

**Comment by ElMoha943** [comment]
just seen this, hold on ima check now. Btw, i believe the problem is in towny expansion as it stopped when i removed it.

**Comment by SirBlobman** [comment]
> 
> 
> just seen this, hold on ima check now. Btw, i believe the problem is in towny expansion as it stopped when i removed it.

That is correct, which is why I made changes to the Towny expansion in the version I sent above.

**Comment by ElMoha943** [comment]
> > just seen this, hold on ima check now. Btw, i believe the problem is in towny expansion as it stopped when i removed it.
> 
> That is correct, which is why I made changes to the Towny expansion in the version I sent above.

Im sorry for taking so long, im waiting for players to leave the server so i can restart. I added the expansion and reloaded the plugin but i think that doesnt work for new expansions. Or if it does its fixed.

**Comment by SirBlobman** [comment]
> 
> 
> > > just seen this, hold on ima check now. Btw, i believe the problem is in towny expansion as it stopped when i removed it.
> > 
> > 
> > That is correct, which is why I made changes to the Towny expansion in the version I sent above.
> 
> Im sorry for taking so long, im waiting for players to leave the server so i can restart. I added the expansion and reloaded the plugin but i think that doesnt work for new expansions. Or if it does its fixed.

I'm sorry, but reloading is not supported. You must restart the server.

**Comment by ElMoha943** [comment]
i restarted and "aparently" its fixed. Thanx you!
