### ISSUE TITLE
PreciousStones Compatability

### ISSUE THREAD

**Issue by SeDark** [SirBlobman/CombatLogX#25]
I am using PvpManager Premium and would like to change it to CombatLogX.

The question is, when they enter combat could they trespass the protections of "PreciousStones"?

**Comment by SirBlobman** [comment]
Not compatible, sorry
I've never heard about "PreciousStones" so I'll need a link to its API so I can add compatability

**Comment by SeDark** [comment]
https://github.com/marcelo-mason/PreciousStones/wiki/Developers-API

**Comment by SirBlobman** [comment]
Thanks for the link, the developer was kind enough to provide an awesome API
I will add compatibility in the next version of CLX

**Comment by SirBlobman** [comment]
Added compatability in version 5.2.2.2 with an expansion
