### ISSUE TITLE
Add config option to prevent Towny members from tagging each other.

### ISSUE THREAD

**Issue by ElMoha943** [SirBlobman/CombatLogX#252]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Every death message shows up as combatlog death. Also members of the same town that somehow manage to tag eachother (with explosions for example) have their friendy fire protection toggled off and can kill each other.

### Reproduction Steps

For messages > just die in any way.

The towny bug > you need to toggle combat with a member of your town in some way, for example with explosions or custom abilitys from mythicmobs or others.

### Expected behaviour

Custom death message to only show when the combat log is what kills the player. Players from the same town not being able to tag each other.

### CombatLogX Version

Server Version: git-Tuinity-"9f3435b" (MC: 1.16.5)
Bukkit Version: 1.16.5-R0.1-SNAPSHOT
Minecraft Version: 1.16.5
NMS Version: 1_16_R3

CombatLogX by SirBlobman
Installed Version: v10.4.2.4-Dev
Latest Version: v10.4.2.3

 Cheat Prevention v15.3
PlaceholderAPI Compatibility v15.1
Towny Compatibility v15.3
WorldGuard Compatibility v15.3
Newbie Helper v15.4
Notifier v15.12

**Comment by SirBlobman** [comment]
The death message issue is already fixed today since commit 345444eb8207eeab8f40a118ab69937a7dfff21c

I'll look into adding an option to prevent Towny members from tagging each other.

**Comment by ElMoha943** [comment]
Where can i download the fixed version?

**Comment by SirBlobman** [comment]
> 
> 
> Where can i download the fixed version?

Dev versions for V10 are available on my Jenkins, in the project `CombatLogX Legacy`.
https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX-Legacy/

**Comment by ElMoha943** [comment]
thanx

**Comment by SirBlobman** [comment]
https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX-Legacy/56/artifact/builder/build/CombatLogX-10.4.2.4-Dev.zip
