### ISSUE TITLE
Konquest

### ISSUE THREAD

**Issue by kacperleague9** [SirBlobman/CombatLogX#255]
### Server Implementation

Paper

### Server Version

1.17.1

### CombatLogX Version

Beta 600

### Plugin

[Konquest](https://www.spigotmc.org/resources/konquest.92220/)

### Explanation

This plugin is a cool kingdom-like thing. (like better towny tbh)

**Comment by SirBlobman** [comment]
Thanks for the request. However, it seems that Konquest is a closed source project. Can you point to me to a place where I can find information about its API?

**Comment by Olivoz** [comment]
Just going to put this here https://github.com/Rumsfield/konquest-doc/issues/4

**Comment by kacperleague9** [comment]
Developer is working on it

**Comment by SirBlobman** [comment]
Beta Versions can be found here:
https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/

This expansion should exist in build 614 and higher.
