### ISSUE TITLE
Safezones need improvement

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#26]
Spigot 1.12.2 latest
CombatLogX 5.2.2.2
Factions 2.13.6
WorldGuard 6.2.2-SNAPSHOT;1710-95b88ea
and a myriad of other plugins, all latest pulls

I installed CombatLogX with expansions
> CheatPrevention.jar
> CompatCrackShot.jar
> CompatFactions.jar
> CompatWorldGuard.jar
> NotCombatLogX.jar​

and configured
```
...
cheat prevention:
  safezone:
    no entry: true
    mode: CANCEL
...
```
My typical world has a central small Factions _SafeZone_ at the spawn point, a larger surrounding _BufferZone_, and an outer _Wilderness_. In the _SafeZone_, entities cannot attack (and players cannot build, but can attack entities). In the _BufferZone_, entities and players can attack each other (but players cannot build). In the _Wilderness_, all activities are allowed. The problem appears to be that if a player attacks a mob while in the _SafeZone_ or the _BufferZone_, they cannot move, and they are reported as
```
[CombatLogX] You cannot enter a safe-zone while you are in combat!
```

What happens now:
- If I enter into combat from within the SafeZone or the BufferZone, I cannot move or turn.

What should happen (IMHO):
- Since entities can attack players in the _BufferZone_, it should not be considered a safe-zone for CombatLogX purposes. Safe-zones should be properly determined based on Factions safe zones and/or WorldGuard protected zones.
- If a player enters into combat outside a safe-zone, they should not be able to enter a safe-zone until combat has expired.
- If a player enters into combat from within a safe-zone, they should be able to move within it, and to leave the safe-zone.

**Comment by SlimeDog** [comment]
Anyone looking at this? I am currently running with
```
...
cheat prevention:
  safezone:
    no entry: false
    mode: CANCEL
...
```
but this is not optimal.

**Comment by SirBlobman** [comment]
Its one of the top things on my todo list. Unfortunately, I'm not really experienced with the source for the safe zones of different plugins so it's a bit difficult to do

**Comment by SlimeDog** [comment]
Thanks. Hopefully, someone will volunteer to assist.

**Comment by ToonBasic** [comment]
Is it safezone for Massive Core factions? I am experienced with this, so I can do this.

**Comment by SlimeDog** [comment]
Yes, MassiveCore/Factions. Thanks @ToonBasic.

**Comment by SlimeDog** [comment]
Were you guys able to connect and make progress?

**Comment by SlimeDog** [comment]
Spigot 1.12.2
CLX 6.0.0.0

Results are the same. What was the improvement in safezone processing?

**Comment by ToonBasic** [comment]
Late response sorry. It hasn't really crossed my mind to do this. I am assuming "BufferZone" is a SafeZone?

**Comment by SirBlobman** [comment]
@SlimeDog 
I changed the way things are detected. If a faction has pvp disabled then it is a safezone and players will be knocked back. Same thing with the WorldGuard region that has pvp set to deny

I also rewrote the knockback code so that players would not fly up into the air

**Comment by SlimeDog** [comment]
@ToonBasic My _BufferZone_ is configured to disallow building; monsters are able to attack. In a safezone, monsters do not attack.

**Comment by SlimeDog** [comment]
Spigot 1.12.2
CLX 6.0.0.0
```
...
cheat prevention:
  prevent opening inventories: false
  teleportation:
    prevent: true
    allow ender pearls: false
  safezone:
    no entry: true
...
```
When I enter combat in either the SafeZone or BufferZone, I cannot move. I just keep getting bounced. Is this the expected behavior? I would like to be able to move, but
- not be able to execute any of the blocked commands
- not be able to enter the SafeZone

Please advise.

**Comment by SlimeDog** [comment]
In my Factions configuration, _SafeZone_ is defined by
```
...
  "version": 1,
  "name": "SafeZone",
  "description": "No building, no monsters",
  "createdAtMillis": 1478051396980,
  "invitations": {},
  "flags": {
    "animals": true,
    "endergrief": false,
    "explosions": false,
    "firespread": false,
    "friendlyfire": false,
    "infpower": true,
    "monsters": false,
    "offlineexplosions": false,
    "open": false,
    "peaceful": true,
    "permanent": true,
    "powerloss": false,
    "pvp": false,
    "zombiegrief": false
  },
...
```
and _BufferZone_ is defined by
```
...
  "version": 1,
  "name": "BufferZone",
  "description": "No building",
  "createdAtMillis": 1488438024295,
  "invitations": {},
  "flags": {
    "animals": true,
    "endergrief": false,
    "explosions": false,
    "firespread": false,
    "friendlyfire": false,
    "infpower": false
    "monsters": true,
    "offlineexplosions": false,
    "open": false,
    "peaceful": false,
    "permanent": true,
    "powerloss": true,
    "pvp": false,
    "zombiegrief": false,
  },
...
```

**Comment by SirBlobman** [comment]
@SlimeDog

The reason this happens is because mobs can still tag players and I did not consider this when coding the safezone detector. The current detector only prevents entry and tagging in zones where "pvp" is set to "false"

**Comment by SlimeDog** [comment]
OK, although pvp:false in both my zones. But monsters can attack in the BufferZone, and vice verse; and players can attack NPEs in both zones (but NPEs cannot engage in the SafeZone).

**Comment by SirBlobman** [comment]
@SlimeDog 
Should be solved in 6.0.1.1
Please download the latest jar from /target/ and if it does not work, reopen this

**Comment by SlimeDog** [comment]
I don't find /target/. Full URL, please.

**Comment by SlimeDog** [comment]
Based on initial testing of 6.0.2.0, it appears that the issues are resolved. Thank you.

NOTE: I have not done rigorous testing of other elements of, or interactions among, CombatLogX, Factions, and etc.

**Comment by SirBlobman** [comment]
@SlimeDog 
Thanks for testing, I will now release this 😃
