### ISSUE TITLE
CMI Vanish

### ISSUE THREAD

**Issue by AlternativeSoap** [SirBlobman/CombatLogX#267]
### Server Implementation

Paper

### Server Version

1.17.1

### CombatLogX Version

Latest

### Plugin

CMI
https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

### Explanation

Add support for CMI vanish like essentials vanish

**Comment by SirBlobman** [comment]
Thanks for the request, however it seems that CMI's current version is on 9.0.2.7 and has a new dependency (CMILib) while the API zip is still on 8.7.8.2. 

Once the author updates their API I'll see if I can add support for CMI 🙂

**Comment by SirBlobman** [comment]
Should be applied in build 643+

https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/
