### ISSUE TITLE
Simple placeholder

### ISSUE THREAD

**Issue by AlternativeSoap** [SirBlobman/CombatLogX#273]
### Server Implementation

Spigot

### Server Version

1.17.1

### CombatLogX Version

Latest from jenkins.
11 Beta

### Plugin

No other plugin

### Explanation

Just add placeholder for toggle enable and disable
Can only find on placeholderapi or combatlogx for 
%combatlogx_time_left%
%combatlogx_enemy_name%
%combatlogx_enemy_health%
%combatlogx_enemy_health_rounded%
%combatlogx_enemy_hearts%
%combatlogx_status%
%combatlogx_in_combat%

But need something for the command /pvp
Example
%combatlogx_toggle%

Showing
true
false

or

on
off

**Comment by SirBlobman** [comment]
https://github.com/SirBlobman/CombatLogX/tree/main/expansion/compatibility#placeholder-list

%combatlogx_newbie_helper_pvp_status%
