### ISSUE TITLE
Include configuration files in the JARs

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#29]
A few requests, packed into one issue.

- Please include _combat.yml_ (why not config.yml like every other plugins?) and _language.yml_ in the JAR, so that they can easily be compared with previous versions (which I save for comparison). The current comparison process involves unzipping the ZIP file, installing the JAR on a clean test directory to generate the YML files, then comparing them with the running versions in a different directory. A lot of work, compared with just having them to hand.
- Please include '_Citizens Compatibility/data.yml_' and _NotCombatLogX/not.yml_ in the JAR as well; same reasoning.
- Please remove the space in '_Citizens Compatibility/_'. It overcomplicates file checking, for no discernible reason.

**Comment by SirBlobman** [comment]
Thanks for the feature suggestion, I will try to do this in future updates, but the config is automatically generated by the code, so I don't usually have a default one
