### ISSUE TITLE
Towny PvP Bug

### ISSUE THREAD

**Issue by hasanas83V2001** [SirBlobman/CombatLogX#3]
When in a town sometimes players don't get combat tagged and in an outpost they never get combat tagged, also can you add an option so we can disable that they can't enter townys in combat?

**Comment by SirBlobman** [comment]
I will add options to disable compatability soon. If the town has pvp disabled, the player will never get tagged

**Comment by hasanas83V2001** [comment]
all towns have pvp enabled yet they don't get tagged

**Comment by hasanas83V2001** [comment]
https://www.youtube.com/watch?v=ZRKS81Q-gG4

**Comment by SirBlobman** [comment]
Strange, thanks for the video. I will look into this

**Comment by SirBlobman** [comment]
I am testing this and strangely cannot replicate the issue
May I have your Towny version, CombatLogX version, Minecraft version, and Spigot/Bukkit version?

**Comment by SirBlobman** [comment]
This should be fixed in version "1.1.5 Release"
if not, please re-open the issue
