### ISSUE TITLE
Config option for default state of PvP toggle

### ISSUE THREAD

**Issue by Caleston** [SirBlobman/CombatLogX#312]
### Server Implementation

Paper

### Server Version

1.17.1

### CombatLogX Version

Java Version: 16.0.2
Java Vendor: Oracle Corporation

Server Version: git-Paper-353 (MC: 1.17.1)
Bukkit Version: 1.17.1-R0.1-SNAPSHOT
Minecraft Version: 1.17.1
NMS Version: 1_17_R1

Dependency Information:  
  - SirBlobmanCore v2.3.2
  - Essentials v2.19.1-dev+26-e43f06b
  - PlaceholderAPI v2.10.9
  - ProtocolLib v4.7.1-SNAPSHOT-b531
  - Towny v0.97.2.10
  - WorldGuard v7.0.6+1cff55f

CombatLogX by SirBlobman
Plugin Version: 11.0.0.0-Beta-687
Spigot Version: 10.4.2.4

Enabled Expansions (10):
 - ActionBar
 - BossBar
  - CheatPrevention
  - CompatEssentialsX
  - CompatPlaceholderAPI
  - CompatTowny
  - CompatWorldGuard
  - DeathEffects
  - NewbieHelper
  - Scoreboard

### Feature Request

In CombatLogX: Newbie Helper, the default state of the PvP Toggle is ON. I would love it if you guys added the option in config to change the default state of the toggle.
For example, I need players to have PvP Toggle OFF by default until players choose to turn it on, but right now everyone starts with PvP Toggle ON. 

Already requested this in early August via ticket on Discord, but apparently it was forgotten.

**Comment by SirBlobman** [comment]
This is already an option in the `Newbie Helper v16.4` configuration file:
```yml
# (This is for the `/togglepvp` command, protection options are above.)
# What is the default PVP status for players?
# Default: true (PVP allowed)
pvp-toggle-default-status: true
```
