### ISSUE TITLE
Boss bar seems to bug out when fighting multiple mobs in quick succession.

### ISSUE THREAD

**Issue by mibby** [SirBlobman/CombatLogX#32]
CombatLogX as of commit https://github.com/SirBlobman/CombatLogX/commit/34e0b977ba07524ebe80a4f30fe5f722c11be82b

When fighting multiple mobs at the same time and killing them in quick succession, the BossBar seems to sometimes bug out. You sometimes get 2 bars for a bit with one frozen - or even sometimes multiple bars stacked on top of each other.

```
  combat timer: 30
  boss bar:
    enable: true
    color: RED
  mobs:
    combat: true
    blacklist:
    - PIG
    - COW
  remove combat on enemy death: true
```

![link](https://i.imgur.com/kkTIYUC.png)

**Comment by SirBlobman** [comment]
Could I have your latest.log file?

**Comment by SirBlobman** [comment]
No response, closing issue
