### ISSUE TITLE
Request to get out of combat

### ISSUE THREAD

**Issue by MavG8ER** [SirBlobman/CombatLogX#321]
### Server Implementation

Paper

### Server Version

1.17.1

### CombatLogX Version

10.4.2.4

### Feature Request

I think it would be pretty cool if you guys added a get out of combat request where you do /clx request [player] and they get a message asking if they want to accept it using /clx forgive. my friends love to mess around on my server and if they have to go then they have to wait for the timer to run out so if you guys could add this that would be great.

**Comment by whoatemycookie8297** [comment]
would be amazing if this was added.
