### ISSUE TITLE
CombatLogX Dont Work With PowerRanks

### ISSUE THREAD

**Issue by DanielGRC3** [SirBlobman/CombatLogX#331]
### Server Implementation

Spigot

### Server Version

1.16.5

### CombatLogX Version

1.16.5

### Plugin

PowerRanks

### Explanation

I would like you to add an extension for the plugin PowerRanks is a NameTagEdit type ranges plugin

### Extra Information

Why when putting PowerRanks CombatLogX nothing works

**Comment by Olivoz** [comment]
Could you be more specific than "nothing works". Are there any errors? What specifically doesn't work. Also make sure you're not op when testing.

**Comment by DanielGRC3** [comment]
It's just like the plugin is missing

**Comment by DanielGRC3** [comment]
I did tests as op and as user

**Comment by Olivoz** [comment]
Did you forget SirBlobmanCore?

**Comment by DanielGRC3** [comment]
nope

**Comment by DanielGRC3** [comment]
I have the plugin

**Comment by Olivoz** [comment]
Are there any errors in the console?

**Comment by DanielGRC3** [comment]
nope the registry and everything is fine in the console I do not see any error

**Comment by SirBlobman** [comment]
> nope the registry and everything is fine in the console I do not see any error

Please post the full `/logs/latest.log` file and the output from `/clx version`.

**Comment by DanielGRC3** [comment]
¿What?

**Comment by SirBlobman** [comment]
> ¿What?

I need you to send this file:
`/logs/latest.log`

I also need you to type this command in your server console and send me what it says:
`clx version`

**Comment by DanielGRC3** [comment]
im use aternos

**Comment by SirBlobman** [comment]
> im use aternos

I'm sorry, but if you don't have access to your server log then I can't help you. We need this information to resolve the issue. I recommend contacting Aternos support to help you with this. Once you can provide the information requested, please reopen the issue.

**Comment by DanielGRC3** [comment]
okay
