### ISSUE TITLE
Support for 1.18*

### ISSUE THREAD

**Issue by Bartek200219** [SirBlobman/CombatLogX#338]
### Server Implementation

Spigot

### Server Version

1.17.1

### CombatLogX Version

![image](https://user-images.githubusercontent.com/37016424/146072475-5a3ba66e-4837-4d5e-9355-988902341baf.png)

### Feature Request

Please add support for 1.18

**Comment by Olivoz** [comment]
You can use the v11 beta builds for 1.18. This will require that you remove all old CombatLogX files.

You can find the beta builds here;
https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/

**Comment by SirBlobman** [comment]
Like Olivo said, 1.18 is supported by V11.
