### ISSUE TITLE
Anti Border Hopping

### ISSUE THREAD

**Issue by NekoShouta** [SirBlobman/CombatLogX#34]
This option will push back a player from a region when he's in combat and tries to enter it. (Like Pvp-Manager)
Players will be vulnerable in safe zones. (Like Pvp-Manager)

https://github.com/NoChanceSD/PvPManager/blob/e54e97640277583e4da470919e706140c00393d6/PvPManager/src/main/java/me/NoChance/PvPManager/PvPManager.java#L81

**Comment by EvilSlime** [comment]
Yes we need this.

**Comment by SirBlobman** [comment]
Knockback now works properly
