### ISSUE TITLE
How do I use the NotCombatLogX extension

### ISSUE THREAD

**Issue by AkariDream** [SirBlobman/CombatLogX#354]
i dont see the config option for NotCombatLogX. :(

**Comment by Olivoz** [comment]
The expansion NotCombatLogX no longer exists. It's been renamed to Damage Tagger. So look for it's config and folder. If it does not exist please send the output from /clx version

**Comment by AkariDream** [comment]
i downloaded it at Spigot
but I cant see any *.yml in the extension folder
![image](https://user-images.githubusercontent.com/71176602/147952547-11696732-2f05-478f-9b73-ee8e35947141.png)
![image](https://user-images.githubusercontent.com/71176602/147952565-559b21ef-cba4-42f1-a728-a7b97261a1d2.png)

**Comment by Olivoz** [comment]
You're using CombatLogX v9. It hasn't been supported for almost 1.5 years now

**Comment by AkariDream** [comment]
> You're using CombatLogX v9. It hasn't been supported for almost 1.5 years now

so where should I download the latest

**Comment by Olivoz** [comment]
It's available on our Spigot page

**Comment by AkariDream** [comment]
> It's available on our Spigot page

I still haven't seen it. do I need to delete the old config?

**Comment by AkariDream** [comment]
> > It's available on our Spigot page
> 
> I still havent seen it. do I need to delete the old config?

I have installed it

**Comment by AkariDream** [comment]
he reminded me that I was still not up to date
