### ISSUE TITLE
Help? Factions compat issue

### ISSUE THREAD

**Issue by RainOfPain125** [SirBlobman/CombatLogX#36]
I was in someones land with a friend, and I struck my friend. Then it tried to knock me out of the land that was deemed a 'safezone' and spammed my chat with such "you can not enter a safezone"

Why would faction land be considerd a safezone?

**Comment by SirBlobman** [comment]
I am going to need more information:
- Minecraft Server Version
- Spigot Version
- CombatLogX Version
- List of expansions
- (optional) List of plugins
- Which factions are you using? (e.g. UUID, Normal, Savage)
- Which version of that plugin? (e.g. 1.0, 2.0)

**Comment by RainOfPain125** [comment]
Minecraft Server Version - 1.12.2
Spigot Version - git-Paper-1399
CombatLogX Version - 6.0.2.0
List of expansions
- Cheat Prevention
- Compat Citizens
- Compat Factions
- CompatPlaceholderAPI
- Compat WorldGuard
(optional) List of plugins
Plugins (64): ActionAnnouncer, AdvancedBan, ArrowTrails, Auctions, AutoRestart, BlowableObsidians, BountyHunters, CFD, ChatFeelings, ChatInjector, ChatItem, ChestRestock, ColoredAnvils, CombatLogX, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CrazyCrates, CrazyEnvoy, DeluxeJoin, DiscordSRV, EasyBackup, EpicRename, Essentials, EssentialsChat, eZProtector, FactionChat, Factions, FastAsyncWorldEdit, Gringotts, HeadDrop, HolographicDisplays, InfoBook, InventoryFull, LuckPerms, MassiveBooks, MassiveCore, mcMMO, mcMMOAction, MessageAnnouncer, Multiverse-Core, NoCheatPlus, NoPlugins, OCMFixer, OpenInv, PerWorldInventory, PlaceholderAPI, Plan, PluginLibrary, ProtocolLib, ServerListPlus, ShulkerBlock, SilkSpawners, SuperTrails, SuperVanish, Tablist, TitleManager, Trading, Vault, VPNGuard, Wild, WorldBorder, WorldEdit, WorldGuard
Which factions are you using? (e.g. UUID, Normal, Savage) Massivecraft Factions
Which version of that plugin? (e.g. 1.0, 2.0) 2.13.7

**Comment by RainOfPain125** [comment]
This also happened, I'm not sure if it's related - https://pastebin.com/U1iYHqkd

**Comment by SirBlobman** [comment]
Yes, that is probably an issue. Make sure all your potions are valid and that you don't have any plugins that add invalid potions. I will be making a huge update soon so hopefully it fixes all the bugs

**Comment by RainOfPain125** [comment]
I don't have any custom potions, though, I am using a custom enchants plugin.

The bug I initially posted was pre-custom enchants ever were on the server, though.

**Comment by SirBlobman** [comment]
@RainOfPain125 
I found the source of the potion issue, can you send me your current config file?

**Comment by SirBlobman** [comment]
Should be fixed in version 6.1.0.0
(Uploading soon)
