### ISSUE TITLE
You can kill yourself to earn rewards.

### ISSUE THREAD

**Issue by spookymgmt** [SirBlobman/CombatLogX#363]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

If you kill yourself with potion of harming, instant damage, bow and arrow, etc. You will gain the rewards as if you were killing another player.

### Reproduction Steps

Latest everything, go and kill yourself with potion, earn reward.

### Expected behaviour

You should not gain ANY rewards for killing yourself.

### CombatLogX Version

1.17.1
Combatlogx Version v10.4.2.4
Cheat prevention v15.3
Citizens Compat v15.4
PlaceholderAPI compat v15.1
Worldguard compat v15.3
Damage tagger v15.1
Logger v15.1
Notifier v15.13
Rewards v15.2

**Comment by SirBlobman** [comment]
Does this issue still occur when using V11?

**Comment by SirBlobman** [comment]
No response for > 1 month, reopen this issue if it is still occuring in V11 @spookymgmt
