### ISSUE TITLE
Memory leak in MobTagger extension

### ISSUE THREAD

**Issue by exzolink** [SirBlobman/CombatLogX#388]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

On entity create event you add "spawn_reason" metadata which dont removed on entity despawn/death events

### Reproduction Steps

-

### Expected behaviour

-

### CombatLogX Version

10.4.2.4

**Comment by Olivoz** [comment]
Metadata is attached to the entity instance, therefor it does not need to be removed on entity death. We do not keep an active reference to the mob or metadata that would keep it in memory.

Do you have a memory dump or something that would indicate that we need to remove the metadata manually?

**Comment by exzolink** [comment]
> Metadata is attached to the entity instance, therefor it does not need to be removed on entity death. We do not keep an active reference to the mob or metadata that would keep it in memory.
> 
> Do you have a memory dump or something that would indicate that we need to remove the metadata manually?

Metadata stores in MetadataStore and dont removes automatically on entity death/unload. Metadata should be removed only manually.
https://imgur.com/HzGKbsI

**Comment by exzolink** [comment]
Would be better to use also paper's EntityRemoveFromWorldEvent too check for metadata.

**Comment by Olivoz** [comment]
Thank you for the information
