### ISSUE TITLE
Combat consent 

### ISSUE THREAD

**Issue by WmMSI** [SirBlobman/CombatLogX#395]
### Server Implementation

Paper

### Server Version

1.18.2

### CombatLogX Version

CombatLogX 10.4.2.4

### Feature Request

Add a mutual consent feature to PvP such that both / all players need to agree to combat prior to doing battle.  This way a player in the world who is attacked gets a msg in chat that asks if they want to fight that player or not. 

Players could set themselves to:
 - PvP anytime anyplace
 - PvP if they accept a challenge
 - PvP never ever

**Comment by SirBlobman** [comment]
There is a pvp toggle command in the Newbie Helper expansion.
