### ISSUE TITLE
Problem with language

### ISSUE THREAD

**Issue by Nevvy** [SirBlobman/CombatLogX#4]
Hi
I'm trying remove all chat messages but when i remove phrases and leave '' or 
plugins is creating missing phrases ;--;

> prefix: '[&aAnti-Logout&r] » '
target: ''
blocked: ''
enderpearl cooldown: ''
quit: ''
fail: ''
action bar: ''
boss bar: '&aANTI-LOGOUT&r » &6%1ss'
reload config: CFG RELOADED
towny:
  no entry: 
scoreboard:
  title: []
  list: []
attack: 
target mob: 
attack mob: 
expire: 
in combat: 
not in combat: 
open inventory: 

Result
>prefix: '[&aAnti-Logout&r] » '
target: ''
blocked: ''
enderpearl cooldown: ''
quit: '&6%s&r wylogowal sie podczas walki!'
fail: ''
action bar: ''
boss bar: '&aANTI-LOGOUT&r » &6%1ss'
reload config: CFG RELOADED
towny:
  no entry: You cannot enter this town while you are in combat!
scoreboard:
  title: []
  list: []
attack: You attacked &5%1s&r! You are now in combat!
target mob: You were attacked by a mob named &5%1s&f! You are now in combat!
attack mob: You attacked a mob named &5%1s&f! You are now in combat!
expire: You are no longer in combat!
in combat: You are still in combat for &b%1s&f seconds!
not in combat: You are not in combat
open inventory: You cannot open storage blocks during combat

**Comment by SirBlobman** [comment]
If the message is null it will be replaced with a default option. You must set it to '', not blank

**Comment by Nevvy** [comment]
I used your advice result is bellow
CFG
>prefix: ''
boss bar: '&aANTI-LOGOUT&r » &6%1ss'
reload config: ''
target: ''
attack: ''
target mob: ''
attack mob: ''
expire: ''
blocked: ''
in combat: ''
not in combat: ''
enderpearl cooldown: ''
quit: ''
fail: ''
action bar: ''
open inventory: ''
towny:
  no entry: ''
scoreboard:
  title: ''
  list:
  - ''
  - ''
  - ''

http://i.imgur.com/bL4lkgA.png

**Comment by SirBlobman** [comment]
My question is "Why would you need to remove all the messages?"
I will try to add support for blank messages though

**Comment by Nevvy** [comment]
I'd like 2 have only boss bar, enderpearl cooldown and quit msg. This setup looks better and i dont have "chat spam"

**Comment by SirBlobman** [comment]
CombatLogX is not really made for that, especially since the enderpearl cooldown doesn't work

The pearl cooldown however, does work here, and I will add a boss bar soon
https://www.spigotmc.org/resources/enderpearl-cooldown.41981/

**Comment by SirBlobman** [comment]
The latest update should fix the blank message issue :)
