### ISSUE TITLE
Doesn't killing after logout

### ISSUE THREAD

**Issue by mrksbgg** [SirBlobman/CombatLogX#401]
### Server Implementation

Spigot

### Server Version

1.12.2

### Describe the bug

I tagged my friend (no op, just default) and then he log outs but when he logs in back he didnt died

### Reproduction Steps

wdym

### Expected behaviour

he gonna died after logout

### CombatLogX Version

10.4.2.4

**Comment by Olivoz** [comment]
If the Citizens Compatability expansion is installed it will spawn an NPC instead of killing the player. If you don't want it delete the jar from the expansions folder and restart.

**Comment by SirBlobman** [comment]
@mrksbgg Your issue has been replied to, if its still occurring after removing the expansion, please reopen this issue.
