### ISSUE TITLE
- seconds when Combat tagged

### ISSUE THREAD

**Issue by EvilSlime** [SirBlobman/CombatLogX#42]
http://prntscr.com/jk94xp players go in - seconds when combat tagged. This only appears to happen when you turned logs to file off. I tried to use log to console but that doesn't work.

**Comment by SirBlobman** [comment]
Are there any errors in your console?
Also, make sure you restart instead or reloading, I cannot replicate this bug

**Comment by EvilSlime** [comment]
http://prntscr.com/jk9ihp If you turn "log to file" off your timer goes to - seconds no errors that's just the case because it doesn't save the log. You should remove those 2 options.
