### ISSUE TITLE
Errors spammed in console after 1.19 update

### ISSUE THREAD

**Issue by DarkKingKaanMC** [SirBlobman/CombatLogX#446]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Errors spammed in console after 1.19 update:
https://pastebin.com/gNaKVEUH

### Reproduction Steps

1. Run an 1.19 server with the plugin installed.

### Expected behaviour

The plugin should work without any errors.

### Screenshots / Videos

https://pastebin.com/gNaKVEUH

### CombatLogX Version

Latest

**Comment by DarkKingKaanMC** [comment]
![TQjQAqd](https://user-images.githubusercontent.com/30384143/176669950-ce9078d2-fa65-4ba8-a2ae-32ce939da10d.png)

I have read the Spigot page. Is there anything I have missed? Thanks.

**Comment by DarkKingKaanMC** [comment]
I'm special sometimes, lol. Only now I saw the beta versions. I'll go try that.

**Comment by DarkKingKaanMC** [comment]
I didn't see the beta versions. I have updated the plugin properly this time.

**Comment by SevenXD-DEV** [comment]
Can you send me the 1.19 updated jar?
