### ISSUE TITLE
CompatTowny works incorrectly

### ISSUE THREAD

**Issue by AIphaDragon** [SirBlobman/CombatLogX#45]
Hello, we have been using your plugin for a long time. Thank you for this development. 
The problem is that in the Towny plugin you can create town arenas with disconnected pvp in the town. It turns out that PVP can only be in the arena for residents of the town. What can be seen from this on the video. And so everything works correctly. Thanks in advance for your help. Write, if you need more information.
Video with problem: https://youtu.be/BUdFics4cNQ
Towny version: 0.92.12 (latest)
CombatLogX version: 7.2.0.0
Server version: spigot 1.12.2

**Comment by SirBlobman** [comment]
I cannot tell what language that is, sorry
I will look into CompatTowny and check for bugs though

**Comment by SirBlobman** [comment]
@AIphaDragon 
Could you test Bleeding Edge - 7.2.0.1 please?
There should be a zip in /target/CombatLogX.zip

**Comment by AIphaDragon** [comment]
Sorry for the long answer. The problem remains: https://youtu.be/dQCr62yv9V8

**Comment by AIphaDragon** [comment]
The problems remains in new plugin version 8.0.0.0

**Comment by SirBlobman** [comment]
@AlphaDragon
Could you try "Bleeding Edge - 8.0.0.1" for me?
Should be in /target/CombatLogX.zip

**Comment by SirBlobman** [comment]
No reply for 3 months, issue closed
