### ISSUE TITLE
Everyone get kicked when an admin is starting a fight against a player

### ISSUE THREAD

**Issue by craftish37** [SirBlobman/CombatLogX#451]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

(Actually 1.19 server)

All the connected players are kicked from the server with error : `Internal Exception: java.lang.IllegalAccessException: Can not set final net.minecraft.util.MinecraftEncryption$b field net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.f to null value`

### Reproduction Steps

Just hit a player while being operator (having "*" perm)

### Expected behaviour

As expected, it shouldn't, then just start a fight

### Screenshots / Videos

[Imgur video](https://i.imgur.com/5dFEJmY.mp4)

### latest log file (if applicable)

https://mclogs.minestrator.com/9AD9uFn

### CombatLogX Version

![image](https://user-images.githubusercontent.com/63811617/177222349-5478605a-25d2-47b1-b8de-cc1f06ebf989.png)

### Anything else?

¯\_(ツ)_/¯

**Comment by Olivoz** [comment]
Doesn't look like something that would be caused by us. If you're using Protocollib, ViaVersion or simillar make sure they are up to date. If it still happens send the output from /clx version.

**Comment by craftish37** [comment]
> Java Version: 17.0.2
> Java Vendor: Oracle Corporation
>
> Server Version: git-Purpur-1693 (MC: 1.19)
> Bukkit Version: 1.19-R0.1-SNAPSHOT
> Minecraft Version: 1.19
> NMS Version: 1_19_R1
>
> Dependency Information:
> - SirBlobmanCore v2.4.0-Dev
> - Citizens v2.0.30-SNAPSHOT (build 2577)
> - Essentials v2.19.5-dev+24-a60f3c0
> - PlaceholderAPI v2.11.2
> - ProtocolLib v5.0.0-SNAPSHOT-b573
> - SuperVanish v6.2.8
> - Towny v0.98.3.0
> - WorldGuard v7.0.8-SNAPSHOT+2200-4a21bf4
>
> CombatLogX by SirBlobman
> Plugin Version: 11.0.0.0-Beta-789
> Spigot Version: 10.4.2.4
>
> Enabled Expansions (9):
> - CompatCitizens
> - CompatEssentialsX
> - CompatLibsDisguises
> - CompatMarriageMaster
> - CompatPlaceholderAPI
> - CompatSuperVanish
> - CompatTowny
> - CompatWorldGuard
> - Rewards
I let you guess it's still not working, even after updating ProtocolLib xD

**Comment by craftish37** [comment]
Fixed by messing with the perms, probably a strange plugin incompatibility, I'll check deeper to see if I can find which 👌

**Comment by SirBlobman** [comment]
@craftish37 Please reopen this if the issue is still occurring.
