### ISSUE TITLE
Citizens Expansion Immunity Issue

### ISSUE THREAD

**Issue by LunaFall** [SirBlobman/CombatLogX#455]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Using the Citizens expansion allows an NPC to be spawned when a player is disconnected during combat. This is a really good feature, but there's a huge downside. Upon a player disconnecting, the NPC will appear but it'll have around 3-4 seconds of immunity. This is really bad since players can repeatedly leave to be immune to any type of damage until they are out of combat.

A fix could be being able to set up the grace time players get upon disconnecting. If the value is 0, make it have no protection/immunity at all.

### Reproduction Steps

1. Use CompactCitizens
2. Make CombatLogX not insta-kill a player upon disconnecting. (kill-time: NEVER)
3. Hit a player and tell them to disconnect.
4. NPC will appear and you won't be able to hit for a good 3-4 seconds.

### Expected behaviour

Expected behavior is to obviously be able to hit the NPC as soon as it appears. Or, atleast, make a modifiable timer for the immunity.

### Screenshots / Videos

https://user-images.githubusercontent.com/41271741/178154930-469c0b76-c5c7-46d0-bf61-f43fa868b616.mp4

### CombatLogX Version

  [Sun 17:09:51 INFO ] Java Version: 17.0.3
  [Sun 17:09:51 INFO ] Java Vendor: Debian
  [Sun 17:09:51 INFO ] Server Version: git-Paper-58 (MC: 1.19)
  [Sun 17:09:51 INFO ] Bukkit Version: 1.19-R0.1-SNAPSHOT
  [Sun 17:09:51 INFO ] Minecraft Version: 1.19
  [Sun 17:09:51 INFO ] NMS Version: 1_19_R1
  [Sun 17:09:51 INFO ] Dependency Information:
  [Sun 17:09:51 INFO ]  - SirBlobmanCore v2.4.0-Dev
  [Sun 17:09:51 INFO ]  - Citizens v2.0.30-SNAPSHOT (build 2596)
  [Sun 17:09:51 INFO ]  - Essentials v2.19.5-dev+26-2bba577
  [Sun 17:09:51 INFO ]  - PlaceholderAPI v2.11.2-DEV-155
  [Sun 17:09:51 INFO ]  - ProtocolLib v5.0.0-SNAPSHOT-b575
  [Sun 17:09:51 INFO ]  - WorldGuard v7.0.8-SNAPSHOT+2201-6efdb10
  [Sun 17:09:51 INFO ] CombatLogX by SirBlobman
  [Sun 17:09:51 INFO ] Plugin Version: 11.0.0.0-Beta-798
  [Sun 17:09:51 INFO ] Spigot Version: 10.4.2.4
  [Sun 17:09:51 INFO ] Enabled Expansions (9):
  [Sun 17:09:51 INFO ]  - ActionBar
  [Sun 17:09:51 INFO ]  - BossBar
  [Sun 17:09:51 INFO ]  - CheatPrevention
  [Sun 17:09:51 INFO ]  - CompatCitizens
  [Sun 17:09:51 INFO ]  - CompatEssentialsX
  [Sun 17:09:51 INFO ]  - CompatPlaceholderAPI
  [Sun 17:09:51 INFO ]  - CompatWorldGuard
  [Sun 17:09:51 INFO ]  - DamageTagger
  [Sun 17:09:51 INFO ]  - Glowing

**Comment by SirBlobman** [comment]
@LunaFall Thank you for reporting this issue, however it seems that this invulnerability is not an option in the Citizens API nor in the Bukkit/Spigot API for players.

Have you tried checking if any other plugins add invulnerability on teleportation/login? I've heard that Essentials has a config option for that.

**Comment by Olivoz** [comment]
I believe this is vanilla protecting the player for the first 3 seconds after joining
