### ISSUE TITLE
Make multiple opponents

### ISSUE THREAD

**Issue by xstramec** [SirBlobman/CombatLogX#456]
### Server Implementation

Spigot

### Server Version

1.17.1

### CombatLogX Version

10.4.2.4

### Feature Request

I'd really like to see it. When you fight with several opponents, there are more rivals in the scoreboard. CombatLogX | Another server with this chip
![image](https://user-images.githubusercontent.com/63367064/178456673-0d2d585b-edcd-40ef-b574-7d8b7924b22d.png)
![image](https://user-images.githubusercontent.com/63367064/178457548-dbb51599-d1da-4f17-96ef-7543713debd5.png)

**Comment by SirBlobman** [comment]
Thank you for the request, you can track this feature in the following PR:
#464

**Comment by SirBlobman** [comment]
@xstramec Please test the following version and tell me if there are any issues:
https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX-Multiple-Enemies/1/
