### ISSUE TITLE
Pct: 4.16%

### ISSUE THREAD

**Issue by MikhailY** [SirBlobman/CombatLogX#47]
What should be done to make the load on the server because of the plugin less?
http://prntscr.com/k6ysvv

**Comment by SirBlobman** [comment]
I don't know. Any suggestions?

**Comment by MikhailY** [comment]
The server should lag like this from ? I have online on a 250+

**Comment by SirBlobman** [comment]
@MikhailY 
Sorry but I do not know what you are asking me to do or change

**Comment by MikhailY** [comment]
I mean can remove the load CPU from the plugin?
