### ISSUE TITLE
Players can push through the CompactWorldGuard KNOCKBACK_PLAYER no-entry-mode fairly easily with a high velocity.

### ISSUE THREAD

**Issue by accLarson** [SirBlobman/CombatLogX#472]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

When using the CompactWorldGuard expansion, with `no-entry-mode: KNOCKBACK_PLAYER` set, players are able to enter regions that are flagged as no-go zones with CombatLogX worldguard flags. This is accomplished by travelling into the region with a high velocity. Once the player has pushed through the region edge, the player is unrestricted from moving around.

No matter the value set to `knockback-strength`, the player can still push through.

### Reproduction Steps

1. Install latest build of CombatLogX
2. Use latest build of CompactWorldGuard
3. `no-entry-mode: KNOCKBACK_PLAYER`
4. define a region with the `player-combat` flag set to deny.
5. engage in pvp and become tagged.
6. use elytra and rockets to attempt to travel into the region
7. push through region wall.

### Expected behaviour

It would be expected that you cannot enter the region no matter the velocity of the player attempting to enter.

### CombatLogX Version

```
[20:12:24 INFO]: 
[20:12:24 INFO]: Java Version: 17.0.2
[20:12:24 INFO]: Java Vendor: Oracle Corporation
[20:12:24 INFO]: 
[20:12:24 INFO]: Server Version: git-Paper-61 (MC: 1.19)
[20:12:24 INFO]: Bukkit Version: 1.19-R0.1-SNAPSHOT
[20:12:24 INFO]: Minecraft Version: 1.19
[20:12:24 INFO]: NMS Version: 1_19_R1
[20:12:24 INFO]: 
[20:12:24 INFO]: Dependency Information:
[20:12:24 INFO]:  - SirBlobmanCore v2.4.1-Dev
[20:12:24 INFO]:  - WorldGuard v7.0.7+216b061
[20:12:24 INFO]:  - Citizens v2.0.30-SNAPSHOT (build 2596)
[20:12:24 INFO]:  - Essentials v2.19.4
[20:12:24 INFO]:  - PlaceholderAPI v2.11.2
[20:12:24 INFO]:  - PremiumVanish v2.7.17
[20:12:24 INFO]:  - ProtocolLib v5.0.0-SNAPSHOT-b575
[20:12:24 INFO]: 
[20:12:24 INFO]: CombatLogX by SirBlobman
[20:12:24 INFO]: Plugin Version: 11.0.0.0-Beta-unofficial
[20:12:24 INFO]: Spigot Version: 10.4.2.4
[20:12:24 INFO]: 
[20:12:24 INFO]: Enabled Expansions (6):
[20:12:24 INFO]:  - ActionBar
[20:12:24 INFO]:  - CheatPrevention
[20:12:24 INFO]:  - CompatCitizens
[20:12:24 INFO]:  - CompatEssentialsX
[20:12:24 INFO]:  - CompatPlaceholderAPI
[20:12:24 INFO]:  - CompatWorldGuard
[20:12:24 INFO]: 
```

**Comment by SirBlobman** [comment]
There are a few options to temporarily resolve this problem.

1) Use the CheatPrevention expansion to disable elytras during combat.
2) Use a different no-entry-mode.

I'll look into fixing this issue in future updates.

**Comment by accLarson** [comment]
Thanks for the quick response providing immediate solutions. 

I personally have chosen to use CANCEL_EVENT mode as a solution however I look forward to a fully functional KNOCKBACK_PLAYER mode.

**Comment by SirBlobman** [comment]
@accLarson This issue should be fixed in 11.0.0.2

**Comment by accLarson** [comment]
Hey SirBlobman,

Players are still able to enter a region with the the flags set to block their entry using KNOCKBACK_PLAYER mode.

This can be done a few ways. 

1. (Easiest method) Entering the region from directly above will cause the player to be bounced out/up once; no matter the knockback strength set in the expansion config, the player is only bounced up about half a block. Once they have been bounced once, they will then fall into the region.

2. With some timing and angulation, if a player flies into the region on an angle and hits a wall within or bordering the region, they can sometimes fall into/enter the region while tagged.

Ive recorded a clip if that's helpful [40 second clip](https://drive.google.com/file/d/1ET7aJGuUt16JIiZ0SoFTVRPCGPkfd9Bx/view?usp=sharing)

**Comment by accLarson** [comment]
Here's how I fixed it in my personal branch of clx:
```
case KNOCKBACK_PLAYER:
                e.setCancelled(true);
                if (player.isInsideVehicle()) {
                    if (!player.leaveVehicle()) {
                        e.setCancelled(true);
                        break;
                    }
                }
```
I added `e.setCancelled(true);` to the `KNOCKBACK_PLAYER` case in `RegionHandler#preventEntry`. The player is still knocked back but if they "overpower" the knockback, they will still be blocked from entering.

**Comment by accLarson** [comment]
Also I'm curious why the `knockbackPlayer` is executed via scheduler rather than just running 
`knockbackPlayer(player, fromLocation, toLocation);`
