### ISSUE TITLE
Expansion Request: Damage Effects

### ISSUE THREAD

**Issue by Henriiig** [SirBlobman/CombatLogX#475]
### Server Implementation

Paper

### Server Version

1.8.8

### CombatLogX Version

11.0.1.0.848

### Feature Request

I would be awesome to have a expansion that allowed the use of particles when a player gets damaged. You could call it a bleeding effect or maybe even change the particle type to your own liking.

**Comment by pastaaxd** [comment]
Yeah, would be cool
