### ISSUE TITLE
Bars for bossbar

### ISSUE THREAD

**Issue by KaspianDev** [SirBlobman/CombatLogX#485]
### Server Implementation

Spigot

### Server Version

1.18.2

### CombatLogX Version

CombatLogX-11.1.0.0.Beta-894

### Feature Request

Pretty straight forward, bars (from action bar extension) but for bossbar :)

**Comment by SirBlobman** [comment]
I'm not really sure how useful this is. The boss bar is already a bar and it should go down with the timer.
