### ISSUE TITLE
Site didn't work

### ISSUE THREAD

**Issue by manul694** [SirBlobman/CombatLogX#490]
### Server Implementation

Paper

### Server Version

1.19.1

### Describe the bug

Site with API didn't work

### Reproduction Steps

1. Going to sirblobman.xyz
2. Hmmm… can't reach this pagenexus.sirblobman.xyz took too long to respond
Try:

Search Bing for [nexus sirblobman xyz](https://www.bing.com/search?form=ANLKDR&q=nexus%20sirblobman%20xyz)
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT

### Expected behaviour

I can get access to sirblobman.xyz

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/48861382/184873753-60076bcc-812a-408c-ad9c-29f5646c3d71.png)
![image](https://user-images.githubusercontent.com/48861382/184873842-f0999bb9-5c8c-4aa4-9ff4-8b735d04bccf.png)

### CombatLogX Version

11.0.1.1.Beta-860

**Comment by SirBlobman** [comment]
@manul694 The server is back online.
