### ISSUE TITLE
Expansion needs update please

### ISSUE THREAD

**Issue by YTPSDanDie** [SirBlobman/CombatLogX#491]
### Server Implementation

Paper

### Server Version

1.19.1

### Describe the bug

The expansion for superiorskyblock doesn’t work as they either renamed or rewritten the plugin and it is now called SuperiorSkyblock2. Appreciate your plugin and the support.

### Reproduction Steps

Install on a server with the updated SuperiorSkyblock2.

### Expected behaviour

For the plugins extension to activate and set compatibility between CombatLogX and SuperiorSkyblock2.

### CombatLogX Version

11.1.0.1.914

![1BAA1D27-08A0-400A-B633-679AFF4D1AAD](https://user-images.githubusercontent.com/60966463/184885713-b43c3b57-52a4-4c95-995b-bbc1edb36aee.jpeg)

**Comment by YTPSDanDie** [comment]
Also I’m on sever version 1.19 atm not 1.19.1.

**Comment by SirBlobman** [comment]
I'm pretty sure I'm using the API version for SuperiorSkyblock2. Can you show me the error from the expansion?

**Comment by YTPSDanDie** [comment]
![577BA71F-780A-4C94-A5E5-2C2D4FAF096E](https://user-images.githubusercontent.com/60966463/184887132-0c9ccf58-1e44-444d-8c52-9e17a2dd751b.jpeg)

**Comment by YTPSDanDie** [comment]
I tried to rename it with the number 3

**Comment by SirBlobman** [comment]
Fixed in v11.1.0.2.915

**Comment by YTPSDanDie** [comment]
SirBlobMan fixed the error very fast thanks again!
