### ISSUE TITLE
Boss Bar Color

### ISSUE THREAD

**Issue by Nevvy** [SirBlobman/CombatLogX#5]
Hi
How can i change boss bar to "old version"?
OLD
![before](https://camo.githubusercontent.com/0d997beedb3659e40f3931634d54c406f031707d/687474703a2f2f692e696d6775722e636f6d2f624c346c6b67412e706e67)
New
![after](http://i.imgur.com/QbjrANg.png)

**Comment by SirBlobman** [comment]
I will add a config option to change the boss bar color

**Comment by SirBlobman** [comment]
Check 4.1.0 Release
