### ISSUE TITLE
Report expansions at start-up

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#50]
Spigot 1.13 latest
CLX 9.0.0.0-b2

Enabled expansions are no longer reported in the console/log at start-up.

**Comment by SirBlobman** [comment]
Will fix, thanks for testing the beta :)

**Comment by SirBlobman** [comment]
Could you send me your latest.log just to be sure?

**Comment by SlimeDog** [comment]
I was mistaken. I see them now. I don't know if I missed them earlier. No point in going back to b1.

Score it as a PEBCAK.
