### ISSUE TITLE
Message's in the action bar instead chat.

### ISSUE THREAD

**Issue by Remski01** [SirBlobman/CombatLogX#509]
### Server Implementation

Paper

### Server Version

1.19.2

### CombatLogX Version

.

### Feature Request

Option to have messages in the action bar instead the chat.

**Comment by SirBlobman** [comment]
Thanks for the request. Did you have any specific messages in mind for this feature?

**Comment by Remski01** [comment]
For me it would be the following: "attacked:" and "attacker:".
