### ISSUE TITLE
instead of second on boss bar and action bar i get {time_left_decimal}

### ISSUE THREAD

**Issue by FreyGon** [SirBlobman/CombatLogX#520]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

Why do I get {time_left_decimal} instead of seconds in the boss bar and action bar?

### Reproduction Steps

1. Downloaded all the necessary add-ons (Action Bar, Boss Bar, Cheat Prevention, Newbie Helper)
2. started the server

### Expected behaviour

I was expecting that when I hit a player, my Boss Bar and Action Bar will show seconds of the end of the pvp zone, instead of seconds I get {time_left_decimal}.

### Screenshots / Videos

![2022-09-24_19 40 40](https://user-images.githubusercontent.com/63667063/192109250-0af579ee-39ac-4243-8ad8-ea96972a8fa7.png)

### CombatLogX Version

11.1.0.6.998

### Anything else?

I am using plugin extension: Boss Bar and Action Bar.

**Comment by SirBlobman** [comment]
@FreyGon Outdated language file, please copy the placeholder from the en_us.lang.yml.

**Comment by FreyGon** [comment]
OMG! Thank bro.
