### ISSUE TITLE
You are attacking N/A. Do not log out!.

### ISSUE THREAD

**Issue by puritynetwork** [SirBlobman/CombatLogX#568]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When I am attacked or attack an enemy it comes out N/A instead of the player's name

### Reproduction Steps

I attack a player 

### Expected behaviour

It should come out the name of the player who attacked me or whom I attacked

### Screenshots / Videos

![Immagine 2022-12-28 200740](https://user-images.githubusercontent.com/120317607/209860756-52fd7490-0bcc-4b12-a573-cf92c44a78b7.png)

### CombatLogX Version

11.1.0.7.1025

**Comment by Olivoz** [comment]
This can happen if you're getting tagged by something else than a player or when the version of Spigot you're running isn't supported. Send the full output from /clx version

**Comment by puritynetwork** [comment]
> This can happen if you're getting tagged by something else than a player or when the version of Spigot you're running isn't supported. Send the full output from /clx version
![Immagine 2022-12-28 202042](https://user-images.githubusercontent.com/120317607/209862080-ff0ff04c-e099-4785-a6a2-93da28a13e35.png)

**Comment by Olivoz** [comment]
That's not 1.19.2.... Use the beta builds available on https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/
