### ISSUE TITLE
Message placeholders not working right.

### ISSUE THREAD

**Issue by Getblock** [SirBlobman/CombatLogX#57]
* **CombatLogX Version**: 9.0.0.0
* **Minecraft Version**:  1.13.2
* **Spigot Version**:  1.13.2

* **List of Expansions**:
notifier v13.3
cheat prevention v13.2

* **What is your issue?**
Language.yml:
attacked by player: "&c&oYou were attacked by &f{name}.&c&o Please do not log out!"
attacker of player: "&c&oYou attacked &f{name}.&c&o Please do not log out!"

![image](https://user-images.githubusercontent.com/43926892/48309954-42617e80-e5bf-11e8-8b90-6af8f825b0f3.png)

as you can see, it shows "attacker of player" hearts symbols instead of the player's name.

**Comment by SirBlobman** [comment]
This is caused by another plugin that changes entity names to hearts. McMMO is most likely the cause.
