### ISSUE TITLE
banfromclaim support

### ISSUE THREAD

**Issue by tanertekin0** [SirBlobman/CombatLogX#580]
### Server Implementation

Paper

### Server Version

1.19.2

### CombatLogX Version

![image](https://user-images.githubusercontent.com/66686400/212042603-e87223ff-edb8-4aa4-92a4-bc24408327f5.png)

### Plugin

https://www.spigotmc.org/resources/banfromclaim.70897/

### Explanation

This style allows players who are banned from the claim to be entered in that claim while they are in pvp.

**Comment by SirBlobman** [comment]
This plugin is an addon for GriefDefender and GriefPrevention. You should use the expansion for those instead and set the mode to VULNERABLE if you want to allow players to enter the areas.
