### ISSUE TITLE
Chickens from Zombie Spawner still enable combat tag (Mobtagger, spawners disabled)

### ISSUE THREAD

**Issue by MCHalfAssed** [SirBlobman/CombatLogX#590]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

My mobtagger config is this:
spawn-reason-list:
  - SPAWNER

When hitting a chicken from a Zombie Spawner, the player becomes combat tagged. 

### Reproduction Steps

Hit a chicken from a Zombie Spawner. 

### Expected behaviour

The Zombies do not enable combat tag. However, the chicken does. 

### CombatLogX Version

30.01 16:21:27 [Server] [INFO] Java Version: 17
30.01 16:21:27 [Server] [INFO] Java Vendor: AdoptOpenJDK
30.01 16:21:27 [Server] [INFO] Server Version: git-Paper-383 (MC: 1.19.3)
30.01 16:21:27 [Server] [INFO] Bukkit Version: 1.19.3-R0.1-SNAPSHOT
30.01 16:21:27 [Server] [INFO] Minecraft Version: 1.19.3
30.01 16:21:27 [Server] [INFO] NMS Version: 1_19_R2
30.01 16:21:27 [Server] [INFO] Dependency Information:
30.01 16:21:27 [Server] [INFO] - BlueSlimeCore v2.6.1.222-Beta
30.01 16:21:27 [Server] [INFO] - Essentials v2.20.0-dev+40-996285c
30.01 16:21:27 [Server] [INFO] - GriefPrevention v16.18
30.01 16:21:27 [Server] [INFO] - PlaceholderAPI v2.11.2
30.01 16:21:27 [Server] [INFO] - PlayerParticles v8.3
30.01 16:21:27 [Server] [INFO] - ProtocolLib v5.0.0-SNAPSHOT-b608
30.01 16:21:27 [Server] [INFO] - WorldGuard v7.0.7+216b061
30.01 16:21:27 [Server] [INFO] CombatLogX by SirBlobman
30.01 16:21:27 [Server] [INFO] Plugin Version: 11.1.0.7.1025
30.01 16:21:27 [Server] [INFO] Spigot Version: 11.1.0.7.1025
30.01 16:21:27 [Server] [INFO] Enabled Expansions (15):
30.01 16:21:27 [Server] [INFO] - ActionBar
30.01 16:21:27 [Server] [INFO] - BossBar
30.01 16:21:27 [Server] [INFO] - CheatPrevention
30.01 16:21:27 [Server] [INFO] - CompatEssentialsX
30.01 16:21:27 [Server] [INFO] - CompatGriefPrevention
30.01 16:21:27 [Server] [INFO] - CompatPlaceholderAPI
30.01 16:21:27 [Server] [INFO] - CompatPlayerParticles
30.01 16:21:27 [Server] [INFO] - CompatWorldGuard
30.01 16:21:27 [Server] [INFO] - DamageTagger
30.01 16:21:27 [Server] [INFO] - DeathEffects
30.01 16:21:27 [Server] [INFO] - Logger
30.01 16:21:27 [Server] [INFO] - LootProtection
30.01 16:21:27 [Server] [INFO] - MobTagger
30.01 16:21:27 [Server] [INFO] - NewbieHelper
30.01 16:21:27 [Server] [INFO] - Scoreboard

**Comment by SirBlobman** [comment]
Unfortunately this is not a CombatLogX issue. The chicken just doesn't have any metadata to identify that it came from a spawner.
