### ISSUE TITLE
CompatLands Still not working

### ISSUE THREAD

**Issue by Dagrond** [SirBlobman/CombatLogX#591]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

So, CompatLands expansion is still not working on latest versions of CLX and Lands. It doesn't matter which "no-entry-mode" I set, the players can go into their Land normally and other player can't attack them when they are combat tagged. No errors in console. Tested on clean server with only lands and clx installed, on paper 1.19.3.

### Reproduction Steps

1. Create land
2. disable "attack player" flag for "outsider" rank
3. exit land claim and get into combat
4. Now, if you're combat tagged, you can simply walk into land. Either you have set "no-entry-mode" to KNOCKBACK_PLAYER or TELEPORT_TO_ENEMY or whatever, it simply does not work. No errors in console.

### Expected behaviour

Well, working like it used to.

### CombatLogX Version

CLX 11.1.0.8.1056
BlueSlimeCore v2.6.2.239-Beta
Lands 6.28.4

**Comment by SirBlobman** [comment]
Should be fixed in the 11.2 beta.
