### ISSUE TITLE
Problem with various {} variables in messages

### ISSUE THREAD

**Issue by Adrian5063** [SirBlobman/CombatLogX#594]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Hello, I noticed a problem with {} variables in CombatLogX plugin messages. Messages of the {time-left-decimal} type are not changed by the plugin at all and are displayed exactly as in the language configuration file. I'm sending a screenshot at the bottom, despite everything, I'm not very good in English.
I installed the default CombatLogX and BlueSlimeCore on the test server and the problem occurs even with the default files.
![2023-01-31_14 58 28](https://user-images.githubusercontent.com/112986097/215781527-f1d90b93-4830-4a8f-a858-b0d33745cf4b.png)

### Reproduction Steps

1. Install Paper 1.19.3 (latest version)
2. Install default CombatLogX (latest version)
3. Install default BlueSlimeCore (latest version)
4. Join server, try hit with another player or mob
5. See problem with {} in messages

### Expected behaviour

I don't quite understand this point, but first of all the plugin should understand {} and change them to appropriate values

### Screenshots / Videos

![2023-01-31_14 58 28](https://user-images.githubusercontent.com/112986097/215782311-16fd0ef0-7a09-427d-8c83-1bca7b0fffb9.png)

### latest log file (if applicable)

https://pastebin.com/4gEhyXeL

### CombatLogX Version

[INFO] .... Java Version: 17.0.1

[INFO] .... Java Vendor: Eclipse Adoptium

[INFO] ....

[INFO] .... Server Version: git-Paper-386 (MC: 1.19.3)

[INFO] .... Bukkit Version: 1.19.3-R0.1-SNAPSHOT

[INFO] .... Minecraft Version: 1.19.3

[INFO] .... NMS Version: 1_19_R2

[INFO] ....

[INFO] .... Dependency Information:

[INFO] .... - BlueSlimeCore v2.6.1.238

[INFO] ....

[INFO] .... CombatLogX by SirBlobman

[INFO] .... Plugin Version: 11.1.0.8.1056

[INFO] .... Spigot Version: 11.1.0.8.1056

[INFO] ....

[INFO] .... Enabled Expansions (11):

[INFO] .... - ActionBar

[INFO] .... - BossBar

[INFO] .... - CheatPrevention

[INFO] .... - DamageTagger

[INFO] .... - DeathEffects

[INFO] .... - Glowing

[INFO] .... - Logger

[INFO] .... - LootProtection

[INFO] .... - MobTagger

[INFO] .... - NewbieHelper

[INFO] .... - Scoreboard

**Comment by Olivoz** [comment]
This is happening because of outdated placeholders. Only the en_us file is official maintained the reset are translated by the community. You can help maintain the translations on our [crowdin page](https://crowdin.com/project/combatlogx-spigot-plugin)

You can take a look at the default en_us file for the working placeholders or look at the placeholder list available [here](https://github.com/SirBlobman/CombatLogX/blob/main/expansion/compatibility/PlaceholderAPI/README.MD). Make sure you replace %% with {} if you're in the CombatLogX language file.

**Comment by Adrian5063** [comment]
Ohh, thanks for help
