### ISSUE TITLE
Performance regression in BossBar expansion

### ISSUE THREAD

**Issue by galacticwarrior9** [SirBlobman/CombatLogX#596]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

As of 11.1.0.8.Beta-1051, the BossBar expansion's update task is intensive. This was not the case for previous versions. It seems this problem emerged after the plugin switched to using MiniMessage.

The following [profile](https://spark.lucko.me/lBcf9PRx48) is from a fight with several players, around 10. 

![Image](https://i.gyazo.com/81b644d7062c220d6b32b4ea1edce66f.png)

### Reproduction Steps

1. Enable the BossBar expansion.
2. Get several players combat-tagged. I would say at least 5 for good measure.
3. Start profiling using spark.

### Expected behaviour

Updating the boss bar should barely register on profiling, as in earlier versions. 

### CombatLogX Version

11.1.0.8.Beta-1051

**Comment by SirBlobman** [comment]
Try the 11.2 beta version and let me know if the performance has improved.
