### ISSUE TITLE
[Feature request] New events for punish/block commands.

### ISSUE THREAD

**Issue by user127001** [SirBlobman/CombatLogX#60]
Hello!
I have a suggestions.
1. Option to block commands during the fall and use of the Elytra. Particularly tricky players use teleportation commands when they realize that falling or colliding with a wall cannot be avoided.
2. Option to punish the player (kill him) when he leaves the server during the fall. Because using such a trick like reconnecting to the server you can avoid fatal damage from falling.

Regards.

**Comment by SirBlobman** [comment]
Interesting ideas. Maybe as a new plugin though since they're not really related to combat stuff

**Comment by SirBlobman** [comment]
@user127001 

FallAvert just detects the block under them, and if its AIR it blocks commands. I'll only update it if its not working. 

Please DM me on Discord since this is not related to CombatLogX 😛 

SirBlobman#7235
