### ISSUE TITLE
WorldGuard expansion error

### ISSUE THREAD

**Issue by craciu25yt** [SirBlobman/CombatLogX#603]
### Server Implementation

Paper

### Server Version

1.8.8

### Describe the bug

If you are tagged and you put a block just in the borded and you jump over it or you spam fireworks you will just bypass the knockback. And with cancel event you just get stuck flying with the elytras

### Reproduction Steps

Be tagged
Spam fireworks with elytras

### Expected behaviour

to be knocked back

### CombatLogX Version

Current lastest (11.1.0.8.1056)

**Comment by Olivoz** [comment]
Elytras don't exist in 1.8.8... Send the actual output from /clx version

**Comment by SirBlobman** [comment]
No reply

**Comment by craciu25yt** [comment]
1.18.2*

**Comment by craciu25yt** [comment]
@SirBlobman reopen it

**Comment by craciu25yt** [comment]
I didn't answer cuz I don't usually login in github
