### ISSUE TITLE
Worldguard Compatibility isn't working

### ISSUE THREAD

**Issue by DeciusLive** [SirBlobman/CombatLogX#610]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

My Worldguard Compatibility isn't working correctly, it doesn't even prevent people from going in worldguard protected areas. I get no Errors in the Console. I use PaperSpigot as Server Jar. I installed BlueSlimeCore, CombatLogX, GeyserMC, Floodgate, ViaVersion, WorldEdit and Worldguard. I use Java and the Acc I tested it with was also playing on Java. The WorldGuard Compatibility is installed correctly.
Here is the Config:

# How should CombatLogX prevent players from entering non-pvp areas?
# Valid Modes:
# DISABLED - Don't do anything, just let them in
# KNOCKBACK_PLAYER - Add some opposite velocity to the player so they are pushed backwards
# CANCEL_EVENT - Cancel the player's move event
# VULNERABLE - Let the player in, but remove their pvp protection
# KILL_PLAYER - Set the player's health to 0
# TELEPORT_TO_ENEMY - Teleport the player to their enemy if they have one, or CANCEL if they don't have one.
# Default: KNOCKBACK_PLAYER
no-entry-mode: "KNOCKBACK_PLAYER"

# This value is only used if 'no-entry-mode' is KNOCKBACK_PLAYER
# How much should the backwards velocity be multiplied by?
# Default: 1.5
knockback-strength: 1.5

# How much time (in seconds) should the plugin wait before sending another 'no-entry' message?
# Default: 30
message-cooldown: 30

### Reproduction Steps

1. I wanted to try this CombatLog Plugin so I installed it and the expansions.
2. I saw it had a Worldguard Expansion, so I wanted to test it.
3. I created a Worldguard Region and set the PvP Flag to false.
4. I used MultiMC to start Minecraft twice at the same time.
5. I tried testing it but nothing happened when I punched my Alt and went into the Worldguard protected Area. 

### Expected behaviour

I expected the Plugin to push me back when I'm in Combat and try to go in a Worldguard protected Area.

### CombatLogX Version

CombatLogX-11.1.0.8.1056

**Comment by Olivoz** [comment]
Looks like you forgot to add our WorldGuard flags. See our documentation page for the list: https://www.spigotmc.org/resources/combatlogx.31689/field?field=documentation

**Comment by DeciusLive** [comment]
thanks, it worked now
