### ISSUE TITLE
Force Field not disappearing after combat timer ends.

### ISSUE THREAD

**Issue by Czopereq** [SirBlobman/CombatLogX#639]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Expansion is loading succesfully, but doesn't work. no-entry-mode: "KNOCKBACK_PLAYER" is set in config, but its not knocking players. Every single value isn't working

### Reproduction Steps

1. Added expansion WorldGuard expansion.
2. Turned on server
3. Player A got anti-logout
4. Player A was trying to get into spawn and got without no problems

### Expected behaviour

Player is knocked out of spawn area

### CombatLogX Version

Plugin Version: 11.2.0.0.1077

**Comment by Olivoz** [comment]
Looks like you forgot to add our WorldGuard flags. See our documentation page for the list: https://www.spigotmc.org/resources/combatlogx.31689/field?field=documentation

In the future follow the bug report template and provide the full output from /clx version

**Comment by Czopereq** [comment]
https://snipboard.io/6XwaEO.jpg, player's antilogout passed and the wall isn't hiding XD
