### ISSUE TITLE
Disable CombatLogX in specified WorldGuard region

### ISSUE THREAD

**Issue by andris155** [SirBlobman/CombatLogX#64]
How to disable CombatLogX in specified WorldGuard region?

**Comment by SirBlobman** [comment]
@andris155 

You cannot disable CombatLogX in a WorldGuard region, but you can set the region to `pvp: false` and nobody can get tagged in it.

**Comment by ToonBasic** [comment]
I'd like to combat the claim @SirBlobman.

Yes, it is possible to "Disable" the AntiCheat within a region. What you can do is check if the player walks into the region and if so, create a Map with a boolean utilizing their UUID and preventing them from flagging anything within CombatLogX.
