### ISSUE TITLE
Newbie Helper Expansion: Force a world to PVP: ON

### ISSUE THREAD

**Issue by Remski01** [SirBlobman/CombatLogX#642]
### Server Implementation

Paper

### Server Version

1.19.3

### CombatLogX Version

Java Version: 17.0.6
Java Vendor: Eclipse Adoptium

Server Version: git-Paper-383 (MC: 1.19.3)
Bukkit Version: 1.19.3-R0.1-SNAPSHOT
Minecraft Version: 1.19.3
NMS Version: 1_19_R2

Dependency Information:
  - BlueSlimeCore v2.6.1.235-Beta
  - CMI v9.3.0.6
  - PlaceholderAPI v2.11.2
  - ProtocolLib v5.0.0-SNAPSHOT-b612
  - WorldGuard v7.0.8-beta-01+cbb2ba7
  - ViaVersion v4.6.1

 CombatLogX by SirBlobman
 Plugin Version: 11.1.0.8.Beta-1051
 Spigot Version: 11.2.0.1.1085

  Enabled Expansions (6):
  - ActionBar
  - BossBar
  - CheatPrevention
  - CompatPlaceholderAPI
  - MobTagger
  - NewbieHelper

### Feature Request

Add an feature to force PvP mode on in an set world.

**Comment by SirBlobman** [comment]
Implemented in beta builds
