### ISSUE TITLE
How to disable glow

### ISSUE THREAD

**Issue by Alfa3712** [SirBlobman/CombatLogX#644]
### Server Implementation

Spigot

### Server Version

1.18.2

### CombatLogX Version

11.2.0.1.1085

### Plugin

combatlogx 

### Explanation

i wanna disable glow but there is no file in glow expansion 

### Extra Information

nothing

**Comment by SirBlobman** [comment]
@Alfa3712 You have to delete the jar for the Glowing expansion and restart the server.
