### ISSUE TITLE
Developer API issue.

### ISSUE THREAD

**Issue by 0xBitMC** [SirBlobman/CombatLogX#653]
### Server Implementation

Spigot

### Server Version

1.19.3

### Describe the bug

The repository you use in this document https://github.com/SirBlobman/CombatLogX/blob/main/api/README.MD which points at https://nexus.sirblobman.xyz/public/ is broken.

### Reproduction Steps

Go to https://github.com/SirBlobman/CombatLogX/blob/main/api/README.MD
Try to access the repo url

### Expected behaviour

No 404 error

### CombatLogX Version

11.3-SNAPSHOT

**Comment by SirBlobman** [comment]
That repository is for automatic maven/gradle dependency management. If you're trying to manually browse the repository, use the URL provided on the 404 page.
