### ISSUE TITLE
Error when stopping server (lands)

### ISSUE THREAD

**Issue by cloakfox** [SirBlobman/CombatLogX#66]
https://pastebin.com/KwBaSkSY

Lands version: 2.7.6.0
PaperSpigot 509 (1.13.2)

**Comment by SirBlobman** [comment]
I have not updated to Lands 2.7 yet. Thanks for the info

**Comment by cloakfox** [comment]
> I have not updated to Lands 2.7 yet. Thanks for the info

Do you have any eta on when you are updating it?

**Comment by SirBlobman** [comment]
I'll update this soon. Haven't had much time irl
