### ISSUE TITLE
Force field bypass with elytras and fireworks.

### ISSUE THREAD

**Issue by craciu25yt** [SirBlobman/CombatLogX#665]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

You can bypass the barrier if you go very fast with elytras and fireworks

### Reproduction Steps

1. Take some elytras
2. Get distance
3. Take some speed
4. Go in

### Expected behaviour

to crash with the wall

### CombatLogX Version

 11.2.0.1.1085

**Comment by SirBlobman** [comment]
Does this problem still occur in the [beta](https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/job/main/) versions?

**Comment by SirBlobman** [comment]
Could not replicate, spammed fireworks at a region for a long time and could not enter.
