### ISSUE TITLE
Trident

### ISSUE THREAD

**Issue by Warrior1321** [SirBlobman/CombatLogX#672]
### Server Implementation

Spigot

### Server Version

1.19.4

### CombatLogX Version

Latest

### Feature Request

Can you add a way to block tridents being used when in combat? people keep running away from battles when in pvp because of the tridents

**Comment by SirBlobman** [comment]
If you are referring to the riptide effect, there is already an option for this in the `Cheat Prevention` expansion (items.yml). This option is set to `false` by default because it uses the `PlayerMoveEvent`
