### ISSUE TITLE
IllegalStateException on Luckperms Context

### ISSUE THREAD

**Issue by jrb326** [SirBlobman/CombatLogX#696]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Version is actually 1.20 Paper.

https://pastes.dev/dsrO5newUG

### Reproduction Steps

Unknown - just errors like this in console on a repeated loop/task.

### Expected behaviour

Not to spam console with this error.

### CombatLogX Version

latest

**Comment by SirBlobman** [comment]
@jrb326 
> java.lang.IllegalStateException: zip file closed

This means that either CombatLogX or the expansion were corrupted or you use a reload system like Plugman.
It could also mean you have malware infecting your jar files, but that is less likely.

Please restart the server and let us know if you find out any more information.
