### ISSUE TITLE
Folia - spam in console

### ISSUE THREAD

**Issue by GitJhopa** [SirBlobman/CombatLogX#699]
### Server Implementation

Paper

### Server Version

1.8.8

### Describe the bug

[latest.log](https://github.com/SirBlobman/CombatLogX/files/12122900/latest.log)

### Reproduction Steps

[latest.log](https://github.com/SirBlobman/CombatLogX/files/12122901/latest.log)

### Expected behaviour

no spam.

### CombatLogX Version

latest.

**Comment by Olivoz** [comment]
That's not 1.8.8 also in the future please provide the exact output from `/clx version`, just like the issue template tells you to.
As for the issue please try and recreate it on the latest beta build of CombatLogX, available [here](https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/job/main/). At the time of posting this reply the Jenkins is down so you can just try the latest BlueSlimeCore from [here](https://www.spigotmc.org/resources/blueslimecore.83189/)

**Comment by SirBlobman** [comment]
Olivo is correct, please update BlueSlimeCore to the version that supports 1.20 and fill out the form properly in the future.
