### ISSUE TITLE
Default Language File "blocked command"

### ISSUE THREAD

**Issue by hasanas83V2001** [SirBlobman/CombatLogX#7]
In the language.yml file, in this string: "blocked command: 'You cannot do /{command} during combat!'" it should be : "blocked command: 'You cannot do {command} during combat!'" without the "/" before "{command}" because with the "/" you'll get (for example) "//fly" and without it you'll get "/fly"

**Comment by SirBlobman** [comment]
I will fix this soon but you won't notice it unless you delete the config :)
