### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by Fallej** [SirBlobman/CombatLogX#705]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

hello! Anti-relog stops working when tps <15

### Reproduction Steps

tps <15

### Expected behaviour

Seconds should be given even with a small tps

### CombatLogX Version

last

**Comment by Olivoz** [comment]
You can change this in the [config.yml](https://github.com/SirBlobman/CombatLogX/blob/b92295a5130228041aba8076bb746718611cd62e/plugin/src/main/resources/config.yml#L124)

**Comment by Fallej** [comment]
> Вы можете изменить это в [config.yml](https://github.com/SirBlobman/CombatLogX/blob/b92295a5130228041aba8076bb746718611cd62e/plugin/src/main/resources/config.yml#L124)

Can you tell me where exactly? A line?

**Comment by Olivoz** [comment]
Line 124 in the default config. I also linked it for you in my comment above

**Comment by Fallej** [comment]
> Line 124 in the default config. I also linked it for you in my comment above

ty
