### ISSUE TITLE
CMI Plugin Compatibility

### ISSUE THREAD

**Issue by Zenya4** [SirBlobman/CombatLogX#71]
CombatLogX Version: v9.2.0.0
Minecraft Version: 1.13.2 
Spigot Version: git-Paper-455 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

List of Expansions:
- WorldGuard
- Cheat Prevention
- Notifier

Related plugin: CMI [https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/updates]

Issue: 
When CombatLogX is used together with CMI, users can still "open" inventories supplied by the plugin. One of these includes "spawner settings" (shift + right-click spawner) which is a feature from CMI. This leads to a duplication glitch where users can get items from inside the settings inventory of the GUI in spawners leading to free spawn eggs.

Why this is reported here:
I feel that CombatLogX should not be allowing the opening of any inventory during combat. I have already set that option in the config to disable inventory interaction during combat, but this is bypassed by some plugins as mentioned above

**Comment by Zenya4** [comment]
To add context, this seems to be more of a problem with the "Cheat Prevention" addon as that is the one which disallows inventory opening during combat

**Comment by SirBlobman** [comment]
Please update to the latest version and tell me if the issue still occurs

**Comment by SirBlobman** [comment]
Closing issue, no reply for 21 days. Reopen this if its still occurring @Zenya4
