### ISSUE TITLE
Colored punish message.

### ISSUE THREAD

**Issue by ninjaguardian** [SirBlobman/CombatLogX#730]
### Server Implementation

Spigot

### Server Version

1.20.1

### Describe the bug

I have this in my config:   - "&9{combatlogx_player}&r left while in combat with &c{combatlogx_current_enemy_name}"
and it wont color.

### Reproduction Steps

Put this(  - "&9{combatlogx_player}&r left while in combat with &c{combatlogx_current_enemy_name}") in the custom-death-message-list: and reload and have someone leave.

### Expected behaviour

For it to be colored.

### CombatLogX Version

11.4.0.1.1193

**Comment by Olivoz** [comment]
Legacy color codes are not supported. Follow the [MiniMessage format](https://docs.advntr.dev/minimessage/format.html)

**Comment by ninjaguardian** [comment]
- "<blue>{combatlogx_player}<white> left while in combat with <red>{combatlogx_current_enemy_name}"
  wont work though

**Comment by ninjaguardian** [comment]
<color:blue>{combatlogx_player}<color:white> left while in combat with <color:red>{combatlogx_current_enemy_name}</color:red>

wont work

**Comment by ninjaguardian** [comment]
can you send an example

**Comment by Olivoz** [comment]
> color:blue{combatlogx_player}color:white left while in combat with color:red{combatlogx_current_enemy_name}</color:red>
> 
> wont work (the < get deleted)

This should work just fine

**Comment by ninjaguardian** [comment]
it wont even load now. it just goes to the originals from the default config.

**Comment by ninjaguardian** [comment]
`custom-death-message-list:
  - "<color:blue>{combatlogx_player}<color:white> left while in combat with <color:red>{combatlogx_current_enemy_name}</color:red>"`

**Comment by Olivoz** [comment]
> it wont even load now. it just goes to the originals from the default config.

That usually means you config is malformed. Send your entire config

**Comment by ninjaguardian** [comment]
```
T# Should CombatLogX punish players when they log out during combat?
# It is not recommended to disable this option unless you are testing something.
# Default: true
on-disconnect: true

# Should CombatLogX punish players when they are kicked from the game?
# Getting kicked from the game is usually not the fault of the player.
# Default: false
on-kick: false

# Should CombatLogX punish players when their timer expires?
# This option is not recommended unless you are testing something.
# Default: false
on-expire: false

# Which kick reasons should not punish players?
# This option is only used when the 'on-kick' option is set to true.
# Default: ["troll", "kicked by SirBlobman"]
kick-ignore-list:
  - "troll"
  - "kicked by SirBlobman"

# Should the kick ignore list be converted into a kick requirement list?
# Default: false
kick-ignore-list-inverted: false

# When should CombatLogX kill the player?
# QUIT: CombatLogX will kill the player the moment they log out.
# JOIN: CombatLogX will kill the player as soon as they log back in.
# NEVER: CombatLogX will never kill the player.
# Default: QUIT
kill-time: QUIT

# This is a list of custom death messages that CombatLogX will use when killing a player.
# A message will be selected from this list randomly.
#
# Valid Placeholders:
# {combatlogx_player} - The name of the player that died.
# {combatlogx_current_enemy_name} - The name of the last enemy that tagged the player. The enemy can be unknown.
#
# If you don't want any custom messages, set this to an empty list
# custom-death-message-list: []
custom-death-message-list:
  - "<color:blue>{combatlogx_player}<color:white> left while in combat with <color:red>{combatlogx_current_enemy_name}</color:red>"

# Should CombatLogX keep track of the amount of times each player was punished?
# Default: true
enable-punishment-counter: true

## If you are searching for the punishment commands, check the 'commands.yml' file.

```

**Comment by Olivoz** [comment]
> ```
> T# Should CombatLogX punish players when they log out during combat?
> # It is not recommended to disable this option unless you are testing something.
> # Default: true
> on-disconnect: true
> 
> # Should CombatLogX punish players when they are kicked from the game?
> # Getting kicked from the game is usually not the fault of the player.
> # Default: false
> on-kick: false
> 
> # Should CombatLogX punish players when their timer expires?
> # This option is not recommended unless you are testing something.
> # Default: false
> on-expire: false
> 
> # Which kick reasons should not punish players?
> # This option is only used when the 'on-kick' option is set to true.
> # Default: ["troll", "kicked by SirBlobman"]
> kick-ignore-list:
>   - "troll"
>   - "kicked by SirBlobman"
> 
> # Should the kick ignore list be converted into a kick requirement list?
> # Default: false
> kick-ignore-list-inverted: false
> 
> # When should CombatLogX kill the player?
> # QUIT: CombatLogX will kill the player the moment they log out.
> # JOIN: CombatLogX will kill the player as soon as they log back in.
> # NEVER: CombatLogX will never kill the player.
> # Default: QUIT
> kill-time: QUIT
> 
> # This is a list of custom death messages that CombatLogX will use when killing a player.
> # A message will be selected from this list randomly.
> #
> # Valid Placeholders:
> # {combatlogx_player} - The name of the player that died.
> # {combatlogx_current_enemy_name} - The name of the last enemy that tagged the player. The enemy can be unknown.
> #
> # If you don't want any custom messages, set this to an empty list
> # custom-death-message-list: []
> custom-death-message-list:
>   - "<color:blue>{combatlogx_player}<color:white> left while in combat with <color:red>{combatlogx_current_enemy_name}</color:red>"
> 
> # Should CombatLogX keep track of the amount of times each player was punished?
> # Default: true
> enable-punishment-counter: true
> 
> ## If you are searching for the punishment commands, check the 'commands.yml' file.
> ```

Seems like you added a `T` before the first #

**Comment by ninjaguardian** [comment]
omg thanks i dont know how i didnt find that
