### ISSUE TITLE
Cheat prevetion exapnsion thing not working HELP WANTED PLSSS

### ISSUE THREAD

**Issue by CreeperCarl12** [SirBlobman/CombatLogX#733]
### Server Implementation

Spigot

### Server Version

1.19.4

### Describe the bug

When i put Cheat prevention in the expasion folder and open it brings up weird code that i do not understand

### Reproduction Steps

dowload cheat prevetion 2. put it in the expasion folder 3. open it

### Expected behaviour

I thought i could open it and cofig it so no one will telepot away when there are in combat

### Screenshots / Videos

![image](https://github.com/SirBlobman/CombatLogX/assets/148410956/7226283e-3bbc-4e51-871e-f1f0e2ae8510)
![image](https://github.com/SirBlobman/CombatLogX/assets/148410956/09e7535e-4070-4d56-9d33-c34c94314c1a)

### latest log file (if applicable)

idk what that means

### CombatLogX Version

Local Version: 11.4.0.1.1193
[03:17:51 INFO]: Remote Version: 11.4.0.1.1193

### Anything else?

when i did clx version it said i only had 3 extensions enabled  and it only had 3 out of the 4 i have and the cheat prevention was not there pls fix
![image](https://github.com/SirBlobman/CombatLogX/assets/148410956/7d4a45f6-d9a9-45b7-9492-ff84fd3abda0)

**Comment by CreeperCarl12** [comment]
I NEED HELP

**Comment by Olivoz** [comment]
You need to open the CheatPrevention folder not the jar itself

**Comment by CreeperCarl12** [comment]
there is no folder

**Comment by Olivoz** [comment]
> there is no folder

You need to start the server once with the expansion installed for the folder to generate. If you've done and still can't see it refresh the view (assuming a web panel or ftp)

**Comment by CreeperCarl12** [comment]
![image](https://github.com/SirBlobman/CombatLogX/assets/148410956/90d80cfe-17ca-439c-b454-150c67a1d493)
 look no foler :(

**Comment by Olivoz** [comment]
If you've restarted the server and it doesn't show up in the output of `/clx version` then check the console for error messages
