### ISSUE TITLE
UltraRegions

### ISSUE THREAD

**Issue by EthanGarey** [SirBlobman/CombatLogX#736]
### Server Implementation

Spigot

### Server Version

1.20.1

### CombatLogX Version

11.4.0.1.1193

### Feature Request

Add ultra regions compatability

**Comment by SirBlobman** [comment]
Thank you, but please fill out the proper [Expansion Request](https://github.com/SirBlobman/CombatLogX/issues/new?assignees=&labels=Feature+Request&projects=&template=expansion-request.yml)
