### ISSUE TITLE
1.14.2 item dupe bug

### ISSUE THREAD

**Issue by successed** [SirBlobman/CombatLogX#74]
This issue here :

1 - The player who escapes from PVP is killed.
2- The player's items fall to the ground.
3 - The player takes the falling items.
4 - The player who has escaped from Pvp enters the game again.
5 - he sees that there is no items falling on the floor, that all the items are on it.
6 - in this way, the player's items are copied from the pvp.

Combatlogx version: 9.7.1.1
Minecraft version: 1.14.2
Server version: 1.14.2

* **List of Expansions (run the command `/clx version`)**:
Expansion list : http://prntscr.com/numjan

**Comment by SirBlobman** [comment]
Can you turn off the `store inventory` option in this file please and tell me if the issue still occurs?

[U]/plugins/CombatLogX/expansions/CompatCitizens/citizens.yml[/U]

**Comment by successed** [comment]
there is a different problem,
The npcs disappears while the chunk is reload.
but when I use this command is /citizens reload, npcs comes back again.

**Comment by successed** [comment]
I'm going to try dupe later and write it here.

**Comment by successed** [comment]
> The part about chunk reloading is not related to clx as far as I know.

nice bug: http://prntscr.com/nupgi0
İ punish for player and the bug... My heart full..

**Comment by SirBlobman** [comment]
This must be a different bug, can you send a video since the picture doesn't really explain it?

**Comment by SirBlobman** [comment]
@successed still a bug?

**Comment by successed** [comment]
> @successed still a bug?

This dupe bug fixed on the store-inventory:false

and

nice bug: http://prntscr.com/nupgi0
İ punish for player and the bug... My heart full..

**Comment by SirBlobman** [comment]
@successed 

Can you send me a video of how this happened? I don't think I fully understand

Try deleting their player data and resetting the citizens expansion

**Comment by successed** [comment]
> @successed
> 
> Can you send me a video of how this happened? I don't think I fully understand
> 
> Try deleting their player data and resetting the citizens expansion

Yeah, this video on bugs: https://youtu.be/r18QzNofy9w

**Comment by SirBlobman** [comment]
Looks weird, can I see the other player's perspective?

**Comment by successed** [comment]
> Looks weird, can I see the other player's perspective?

They see this way in the players and when they reload of the game they get fixed.

**Comment by SirBlobman** [comment]
What I mean is this:

Can I see a video from the player that this happens to?

**Comment by successed** [comment]
> What I mean is this:
> 
> Can I see a video from the player that this happens to?

They see this way in the players and when they reload of the game they get fixed.

**Comment by SirBlobman** [comment]
I cannot replicate this issue, try deleting their playerdata file and make sure you don't have plugins that mess with player health (e.g. set it to NaN or infinity or 9999999999 extra)

**Comment by successed** [comment]
> I cannot replicate this issue, try deleting their playerdata file and make sure you don't have plugins that mess with player health (e.g. set it to NaN or infinity or 9999999999 extra)

This problem is on the gamemode players not else.
