### ISSUE TITLE
Hex Colors do not work

### ISSUE THREAD

**Issue by DrBotz** [SirBlobman/CombatLogX#741]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Hex colors dont work

### Reproduction Steps

NA

### Expected behaviour

NA

### Screenshots / Videos

NA

### latest log file (if applicable)

NA

### CombatLogX Version

NA

### Anything else?

NA

**Comment by Olivoz** [comment]
We cannot help you without any information

**Comment by DrBotz** [comment]
It is so simple, you add &#hexcolorhere and it does not show that color in the message.

**Comment by Olivoz** [comment]
That's not how you add hex colors codes. CombatLogX does not support legacy color codes nor does it implement that pattern. The plugin uses the MiniMessage format, you can read more about it [here](https://docs.advntr.dev/minimessage/format.html)
