### ISSUE TITLE
[!] The player ends up not dying when leaving the server

### ISSUE THREAD

**Issue by caiobarnes** [SirBlobman/CombatLogX#748]
### Server Implementation

Spigot

### Server Version

1.20.1

### Describe the bug

When the player leaves the server while in combat, they do not actually die, and their items are not dropped, etc.

### Reproduction Steps

1. Enters combat
2. Leaves the server/Quits"

### Expected behaviour

I expected him to die, dropping the items on the ground.

### Screenshots / Videos

https://youtu.be/98BlvIdTl-g

### latest log file (if applicable)

https://mclo.gs/QZqbSfL

### CombatLogX Version

CombatLogX 11.4.0.1.1193

### Anything else?

Would it be this.

**Comment by Olivoz** [comment]
Looking at your log the issue would most likely be that you have the `Citizens compatibility` expansion installed. It will spawn an NPC (dummy player by default) instead of killing the player. If this is not what you want then delete the expansion and restart.

**Comment by SirBlobman** [comment]
> [20:07:31 INFO]: - Citizens Compatibility v17.9

When the `Citizens Compatibility` is installed it spawns an NPC instead of killing players. Remove the expansion.
