### ISSUE TITLE
Worldguard Extension not preventing entry properly

### ISSUE THREAD

**Issue by Segysmundo** [SirBlobman/CombatLogX#75]
* **CombatLogX Version**: 9.7.1.3
* **Minecraft Version**: 1.13.2
* **Spigot Version**: PaperSpigot-630 1.13.2

* **List of Expansions (run the command `/clx version`)**: WorldGuard v14.2

* **What is your issue? Make sure you type what the actual bug is and how it can be reproduced.** 

Probably related with #48 

If a player repeatedly attempts to get into a protected region while combat tagged or gets constantly pushed into it he will be able to pass through. It happens too often to not take it into consideration.

**Comment by SirBlobman** [comment]
@Segysmundo 

Thanks for reporting this issue. I have a few more questions that might help this issue get solved.

What version of WorldGuard and ProtocolLib are you using?
Do you have a video of the issue occurring?
What is your `WorldGuard Compatibility` expansion config?
Do you have ViaVersion or ProtocolSupport installed?

**Comment by Segysmundo** [comment]
> @Segysmundo
> Thanks for reporting this issue. I have a few more questions that might help this issue get solved.
> What version of WorldGuard and ProtocolLib are you using?
> Do you have a video of the issue occurring?
> What is your WorldGuard Compatibility expansion config?
> Do you have ViaVersion or ProtocolSupport installed?

WorldGuard **7.0.0**
ProtocolLib **4.4.0**
**[Wordlguard Expansion Config](https://pastebin.com/m48sbzxP
)**
Yes we got ProtocolSupport

**Comment by SirBlobman** [comment]
Should be fixed in 9.8.0.0
