### ISSUE TITLE
Option to hide action bar on server restart.

### ISSUE THREAD

**Issue by mibby** [SirBlobman/CombatLogX#76]
When the server restarts, CombatLogX pops an action bar message up saying you are no longer in combat, even if they weren't in combat. I believe this is due to a check that forces everyone out of combat on server shutdown to prevent combat logging actions caused by the server's fault. However I idle connections and force players to reconnect to the server automatically on scheduled restarts.

Would it be possible to add an option to hide this actionbar message on shutdown?

**Comment by SirBlobman** [comment]
Will add an option soon, thanks for the request.

**Comment by mibby** [comment]
Thanks, I'd really appreciate it!
