### ISSUE TITLE
Ender pearls cause combat tag damage

### ISSUE THREAD

**Issue by ferryside** [SirBlobman/CombatLogX#768]
### Server Implementation

Paper

### Server Version

other

### Describe the bug

Players receive combat tag when using ender pearls when combat tagging is not set to occur when fall damage is taken. Players do not receive combat tag when regular fall damage is taken.

### Reproduction Steps

1. Implement plugin into paper server 1.20.2
2. Set all-damage to false in DamageTagger config.yml
3. Set fall damage to false in DamageTagger config.yml
4. Use ender pearl in game, receive combat tag

### Expected behaviour

Player is not combat tagged.

### CombatLogX Version

Clx 17.0.9
Paper version 318 (1.20.2)
Damage Tagger 17.1

### Anything else?

I was unable to find a damage type specific to ender pearl fall damage in DamageTagger config.yml.

**Comment by Olivoz** [comment]
Please follow the issue template and provide the output from `/clx version`
I do believe ender pearls deal regular fall damage and do not have their own damage type. As for your issue I'm unable to recreate it using the steps provided.
