### ISSUE TITLE
Action bar do not work

### ISSUE THREAD

**Issue by Evalutik** [SirBlobman/CombatLogX#769]
### Server Implementation

Spigot

### Server Version

other

### Describe the bug

Action Bar extention just do not work ;(
server: PurPur 1.20.2

### Reproduction Steps

Just install extention

### Expected behaviour

Should show

### CombatLogX Version

11.4.0.1.1193

**Comment by Olivoz** [comment]
Please follow the issue template and provide the output from `/clx version`. 

The version of CombatLogX you're using does not fully support 1.20.2, update to the [latest development build](https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/job/main/).

**Comment by Evalutik** [comment]
> Please follow the issue template and provide the output from `/clx version`.
> 
> The version of CombatLogX you're using does not fully support 1.20.2, update to the [latest development build](https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/job/main/).

Thanks, I think its better with this version!
Should be updated on spigot
