### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by ArtelGG** [SirBlobman/CombatLogX#77]
**Describe the bug**
One (or more) of the message keys was not updated within the plugin after a change, I presume.

**To Reproduce**
Run `/ct <anotherPlayer>`

**Expected behaviour**
It should send me the proper response (located under `time left other`), instead, it searches for the old message key.

**Screenshots**
https://i.imgur.com/TX6QBdA.png

**Minecraft Version**
https://i.imgur.com/GnM39Yg.png

**CombatLogX Version:**
https://i.imgur.com/GnM39Yg.png

**Additional context**
N/A

**Comment by SirBlobman** [comment]
Which version did you upgrade from? Try removing your language.yml and letting it regenerate

**Comment by ArtelGG** [comment]
I have not upgraded at all, this is occurring with a freshly generated language.yml file

**Comment by SirBlobman** [comment]
I see now. This should be fixed soon
