### ISSUE TITLE
Error command detect

### ISSUE THREAD

**Issue by xGlenor** [SirBlobman/CombatLogX#78]
Hi, i have a problem,I have a blocked commands: /spawn /home /sethome /espawn /ehome /esethome, I'm not sure if this is a bug, but the plugin does not block commands written with uppercase letters

**Comment by SirBlobman** [comment]
Can you turn on debug mode and sent any messages that show up related to commands plz?

**Comment by xGlenor** [comment]
Blocked commands: http://prntscr.com/odtwfe 

When using the command /spawn: http://prntscr.com/odtww7

When using the command /SPAWN: http://prntscr.com/odu1i0

**Comment by SirBlobman** [comment]
Interesting, thanks for the info. I will fix
