### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by NixsSa2d** [SirBlobman/CombatLogX#786]
### Server Implementation

Spigot

### Server Version

1.19.4

### Describe the bug

I'm having problems since the "&" doesn't work, it only works with "§" but I try to change all of them to that and there are errors so I don't understand, how do I make the & work?

### Reproduction Steps

.

### Expected behaviour

.

### CombatLogX Version

11.4.0.0.1156

### Anything else?

no

**Comment by Olivoz** [comment]
Legacy color codes are not supported. CombatLogX uses the [MiniMessage Format](https://docs.advntr.dev/minimessage/format.html)
