### ISSUE TITLE
CombatLog x , appears as red in the plugin list , meaning it doesnt work

### ISSUE THREAD

**Issue by Unblocked4u** [SirBlobman/CombatLogX#795]
### Server Implementation

Spigot

### Server Version

1.19.4

### Describe the bug

CombatLog x , appears as red in the plugin list , meaning it doesnt work. I have tried removed and adding the latest version for both combat log as well as all the other expansions. I dont know what to do nomore.
![2024-01-13_21 56 22](https://github.com/SirBlobman/CombatLogX/assets/154447206/4e89d21b-5a04-4e7f-ae91-d9bed713ce46) 

Here is my servers logs from mclo.gs : https://mclo.gs/xLyTuXw

### Reproduction Steps

See the image for the error , also i find this in the logs :
[12:31:41 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'CombatLogX.jar' in folder 'plugins'
![2024-01-13_21 56 22](https://github.com/SirBlobman/CombatLogX/assets/154447206/84efab53-2cd0-489e-9eec-2edd775faf4f)

### Expected behaviour

My combatLog to be green and working
![2024-01-13_21 56 22](https://github.com/SirBlobman/CombatLogX/assets/154447206/68e5643b-a95a-48de-97df-c1ddd76ced3d)

### Screenshots / Videos

![2024-01-13_21 56 22](https://github.com/SirBlobman/CombatLogX/assets/154447206/f655744f-049c-41e6-8d28-6b575adf3a95)

### latest log file (if applicable)

 https://mclo.gs/xLyTuXw

### CombatLogX Version

latest from spigot

### Anything else?

Nope , thank you very much

**Comment by Olivoz** [comment]
You most likely did not use the BlueSlimeCore jar bundled with CombatLogX

**Comment by Unblocked4u** [comment]
do i just upload blueslimecore in the plugins folder or somewhere else

**Comment by Olivoz** [comment]
Place it in your plugins folder and make sure to delete the old one

**Comment by Unblocked4u** [comment]
ok thx so much. I will get back to you if that didnt fix it. BTW i recommend making a discord server for combat log x , since i didnt find any. I love the plugin so much i can even help you to set it up

**Comment by Olivoz** [comment]
We do have one. It's linked on both the Spigot page and the in the Github readme

**Comment by Unblocked4u** [comment]
ok. Thx btw it works now

**Comment by Unblocked4u** [comment]
i dont find the discord. Are u sure u have it up in spigot
?

**Comment by Olivoz** [comment]
Yes, click the `Ask Questions / Get Support` button

**Comment by Unblocked4u** [comment]
Very good & quick support. Also maybe the best combat logger with tons of extencions. Recommended
