### ISSUE TITLE
dropping items

### ISSUE THREAD

**Issue by R-efil** [SirBlobman/CombatLogX#796]
### Server Implementation

Spigot

### Server Version

1.20.1

### Describe the bug

when in combat players cant drop items

### Reproduction Steps

1. get tagged or tag someone
2. try drop item

### Expected behaviour

items should be able to be thrown onto the floor even if in combat

### CombatLogX Version

latest version

**Comment by Olivoz** [comment]
Please follow the issue template and provide the output from `/clx version` when creating an issue.
Dropping items is configurable in the CheatPrevention expansion. see the [items.yml](https://github.com/SirBlobman/CombatLogX/blob/743c0032611fe69f4ed5d775f3e9a8fb288b7f93/expansion/cheat-prevention/src/main/resources/items.yml#L3)

**Comment by R-efil** [comment]
[Sun 18:20:43 INFO ] Local Version: 11.4.0.1.1193
  [Sun 18:20:43 INFO ] Remote Version: 11.4.0.1.1193
  thats what version im running or says in console at least.
  
  i understand its in items.yml and prevent drop is set to false and it still doesnt work

**Comment by Olivoz** [comment]
Provide the *entire* output from `/clx version`, and the items.yml. Also did you restart or use `/clx reload` after changing the config?

**Comment by R-efil** [comment]
![image_2024-01-14_193529567](https://github.com/SirBlobman/CombatLogX/assets/63607111/c418cf0d-af64-47dc-8812-a16138204b83)
![image_2024-01-14_193545426](https://github.com/SirBlobman/CombatLogX/assets/63607111/8d91696f-4346-430c-aad6-5ba47a49fe51)

we have done clx reload and also restarted the server

**Comment by Olivoz** [comment]
Make sure you've disabled the combat logging from GriefPrevention

**Comment by R-efil** [comment]
ah yes its working now thank you
