### ISSUE TITLE
LibDisguise Combat

### ISSUE THREAD

**Issue by panda** [SirBlobman/CombatLogX#81]
**What minecraft version are you currently using?**
![image](https://user-images.githubusercontent.com/7886355/61836361-eb01f680-ae4d-11e9-85d0-93845c2d8470.png)

**What is your feature request?**
Hi so,

I was seeing if it was possible to add an expansion for LibDisguises, when players are disguised and they enter combat, they are immediately undisguised.

**Comment by SirBlobman** [comment]
This feature is already possible.

In config.yml there is an option for sudo commands on combat

You can add "/undisguise" in there and the player will lose their disguise
