### ISSUE TITLE
500 dollars each kill?

### ISSUE THREAD

**Issue by Loofue** [SirBlobman/CombatLogX#811]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Every time a player kills another player it takes 500 from the player that was killed and puts it into the player that killed that player. 

### Reproduction Steps

![image](https://github.com/SirBlobman/CombatLogX/assets/162374188/e4b5dbe4-d77c-4b07-bee8-0ca1459ce6c5)
![image](https://github.com/SirBlobman/CombatLogX/assets/162374188/a35cb427-a6c5-4d06-acd3-7f9d04931f55)

### Expected behaviour

I expected nothing to happen when they get killed they shouldnt receive 500 dollars.

### Screenshots / Videos

![image](https://github.com/SirBlobman/CombatLogX/assets/162374188/e4b5dbe4-d77c-4b07-bee8-0ca1459ce6c5)
![image](https://github.com/SirBlobman/CombatLogX/assets/162374188/a35cb427-a6c5-4d06-acd3-7f9d04931f55)

### CombatLogX Version

newest

**Comment by SirBlobman** [comment]
Configure or remove the expansion named "Rewards".

**Comment by Loofue** [comment]
thank you!!
