### ISSUE TITLE
enderpearl cooldown

### ISSUE THREAD

**Issue by jitesh1234567** [SirBlobman/CombatLogX#819]
### Server Implementation

Paper

### Server Version

other

### CombatLogX Version

letest

### Plugin

lifestealcore etc

### Explanation

because of enderpearl cooldown

**Comment by Olivoz** [comment]
I have no idea what this is supposed to mean

**Comment by SirBlobman** [comment]
Please fill out the feature request form with proper explanations so we can add your request. If you need enderpearl cooldown, use the CooldownsX plugin.
