### ISSUE TITLE
WorldGuard Compatibility Expansions

### ISSUE THREAD

**Issue by Gyxuu** [SirBlobman/CombatLogX#822]
### Server Implementation

Paper

### Server Version

other

### Describe the bug

Probably a dumb bug report, but where do you download the WorldGuard Compatibility expansion?

### Reproduction Steps

None

### Expected behaviour

Work

### CombatLogX Version

Newest

**Comment by Olivoz** [comment]
All expansions come in CombatLogX zip file. 

I recommend heading over to our discord for smaller questions like this.

**Comment by Gyxuu** [comment]
how do i set up a region that shouldnt be enterred during combat?

**Comment by Olivoz** [comment]
Add our WorldGuard flag(s) to the region. See the [documentation](https://www.spigotmc.org/resources/combatlogx.31689/field?field=documentation) for a list of flags.

**Comment by Gyxuu** [comment]
so player-combat: DENY?
