### ISSUE TITLE
CombatLogX error

### ISSUE THREAD

**Issue by Exst1** [SirBlobman/CombatLogX#825]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

[message_1.txt](https://github.com/SirBlobman/CombatLogX/files/15213147/message_1.txt)
what is the reason of this

### Reproduction Steps

ok

### Expected behaviour

solving the problem

### CombatLogX Version

CombatLogX v11.4.0.2.Beta-1226

**Comment by Olivoz** [comment]
Should be fixed in beta build 1234

**Comment by homerek111** [comment]
> Should be fixed in beta build 1234

@Olivoz Can you please unmute me on discord as I am reporting a bug and got automatically muted for 7d after pinging you XD I have opened ticked #ticket-homerek
