### ISSUE TITLE
i want to disable fall damage tagger

### ISSUE THREAD

**Issue by THEDANImmm** [SirBlobman/CombatLogX#826]
### Server Implementation

Spigot

### Server Version

other

### CombatLogX Version

the newest

### Plugin

i want to disable the fall damage and to disable lava tagger both

### Explanation

please tell me how 

### Extra Information

no more

**Comment by Olivoz** [comment]
For questions like this I recommend heading over to the discord or using the Spigot discussion page. As for your question, delete the damage tagger expansion if you don't want people to be tagged by non-pvp and non-pve damage causes. Alternatively you can configure the expansion to disable the specific damage cause you don't want to tag.
