### ISSUE TITLE
Could not pass event PlayerInteractEvent to CombatLogX v11.4.0.1.1193, plugin don't like short grass

### ISSUE THREAD

**Issue by WXRDI** [SirBlobman/CombatLogX#827]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Could not pass event PlayerInteractEvent to CombatLogX v11.4.0.1.1193
java.lang.IllegalArgumentException: Unsupported material with no data value: SHORT_GRASS

Plugin still works but this kinda embarrassing me 

### Reproduction Steps

1 hit someone 2 break short grass

### Expected behaviour

I can break grass but i cant break other stuff. Expected to stop me from stealing grass while pvp

### Screenshots / Videos

![Снимок экрана 2024-05-06 212405](https://github.com/SirBlobman/CombatLogX/assets/136255117/ba77ef9f-b7fc-48a4-95cb-4844e063fb8c)

### CombatLogX Version

11.4.0.1.1193

**Comment by SirBlobman** [comment]
Similar to #824 and already resolved in beta builds.
