### ISSUE TITLE
Combat log timer is set to max with combat.self false

### ISSUE THREAD

**Issue by MedicOP** [SirBlobman/CombatLogX#83]
The combat timer is set to max each time a player hits themselves with an arrow even though combat.self is set to false.

**Comment by SirBlobman** [comment]
@MedicOP 
I need a screenshot of "/clx version" please

**Comment by MedicOP** [comment]
![image](https://user-images.githubusercontent.com/18251099/62092235-ae326700-b274-11e9-92fe-cccea4f94b92.png)

**Comment by MedicOP** [comment]
https://github.com/SirBlobman/CombatLogX/blob/master/API/src/main/java/com/SirBlobman/combatlogx/utility/CombatUtil.java#L137
Time is always updated if the player is already in combat, there is no check for self-damage here

**Comment by SirBlobman** [comment]
Will fix, thanks for the info. That's not where that check should be anyways, try the CombatListener instead

**Comment by SirBlobman** [comment]
Fixed in 9.9.0.0
