### ISSUE TITLE
Error on hit

### ISSUE THREAD

**Issue by mihiblu** [SirBlobman/CombatLogX#837]
### Server Implementation

Spigot

### Server Version

1.21

### Describe the bug

Here is the error: https://mclo.gs/R0BSR8T

### Reproduction Steps

1. Hit a player on Paper, 1.21

### Expected behaviour

This error appear each time when a player is hit by another.

### CombatLogX Version

[10:22:40 INFO]:  - BlueSlimeCore v2.9.6.431
[10:22:40 INFO]: CombatLogX by SirBlobman
[10:22:40 INFO]: Local Version: 11.5.0.0.1242
[10:22:40 INFO]: Remote Version: 11.5.0.0.1242
[10:22:40 INFO]: Enabled Expansions (10):
[10:22:40 INFO]:  - Action Bar v17.3
[10:22:40 INFO]:  - Cheat Prevention v17.7
[10:22:40 INFO]:  - EssentialsX Compatibility v17.2
[10:22:40 INFO]:  - LuckPerms Compatibility v17.1
[10:22:40 INFO]:  - PlaceholderAPI Compatibility v17.2
[10:22:40 INFO]:  - WorldGuard Compatibility v17.3
[10:22:40 INFO]:  - Damage Effects v17.2
[10:22:40 INFO]:  - Damage Tagger v17.1
[10:22:40 INFO]:  - Glowing v17.0
[10:22:40 INFO]:  - Scoreboard v17.1

**Comment by PabloGirol** [comment]
I have the same issue, seems to be an issue caused by spigot by changing the type of the original Class to an Interface...

**Comment by SirBlobman** [comment]
Set the option  `close-on-retag` to false in inventories.yml for the `Cheat Prevention` expansion. I'm not sure why Spigot decided to change that class file and break plugins 😐

**Comment by Olivoz** [comment]
I believe Spigot uses ASM to patch plugins to maintain backwards compatibility. Now the problem is that CombatLogX uses it's own expansion class loader which doesn't do that. Might be worth looking in to if we can hook that [system](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/util/Commodore.java).

**Comment by mihiblu** [comment]
> Set the option `close-on-retag` to false in inventories.yml for the `Cheat Prevention` expansion. I'm not sure why Spigot decided to change that class file and break plugins 😐

Thank you so much for your answer! If I change only close-on-retag the error still appear but I disabled all things from there and is fine now.

**Comment by SamsimIsMe** [comment]
disabling close-on-retag doesnt work for me

**Comment by Olivoz** [comment]
> disabling close-on-retag doesnt work for me

Try disabling [close](https://github.com/SirBlobman/CombatLogX/blob/a3a49891a4772c415d75a6b8304fae0e585bcc6b/expansion/cheat-prevention/src/main/resources/inventories.yml#L3) as well

**Comment by SamsimIsMe** [comment]
still doesnt work olivoz

**Comment by Olivoz** [comment]
> still doesnt work olivoz
I'm unable to recreate the issue with the settings disabled. Please open your own [GitHub issue](https://github.com/SirBlobman/CombatLogX/issues/new?assignees=&labels=Bug&projects=&template=bug-report.yml) and provide the required information.
