### ISSUE TITLE
Could not pass event PlayerTagEvent to CombatLogX v11.5.0.0.1242 Error every time someone gets hit

### ISSUE THREAD

**Issue by UnsexSituation** [SirBlobman/CombatLogX#839]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

Console is being spammed with "Could not pass event PlayerTagEvent to CombatLogX v11.5.0.0.1242" every time someone gets hit.

### Reproduction Steps

1. Download the Plugin (+ Install)
2. Run the Server

### Expected behaviour

An Error shouldn't happen

### latest log file (if applicable)

https://mclo.gs/LufOuKC

### CombatLogX Version

11.5.0.0.1242

**Comment by Olivoz** [comment]
Related to #837

**Comment by UnsexSituation** [comment]
Yeah that fixed it. Thanks
