### ISSUE TITLE
Citizens NPC is not removed on server restart

### ISSUE THREAD

**Issue by MedicOP** [SirBlobman/CombatLogX#84]
If the server is stopped/restarted while a CombatLogX NPC is active, the NPC is never removed.

Changing this line to npc.destroy(); might solve the issue (not tested):
https://github.com/SirBlobman/CombatLogX/blob/master/expansion/CompatCitizens/src/main/java/com/SirBlobman/expansion/citizens/trait/TraitCombatLogX.java#L34

**Comment by SirBlobman** [comment]
Thanks for the suggestion, this would be better as a pull request instead of an issue though

**Comment by MedicOP** [comment]
I tried but I can't get the maven working, requires way too many dependencies such as SirBlobmanAPI which can not be found anywhere and every version of spigot

**Comment by SirBlobman** [comment]
Makes sense

To get every spigot version just run buildtools with `--rev <version>` for each one
SirBlobmanAPI is [here](https://github.com/SirBlobman/SirBlobmanAPI)

**Comment by SirBlobman** [comment]
Should be fixed in 9.9.0.0, if its not please reopen this issue
