### ISSUE TITLE
Npc item dupe

### ISSUE THREAD

**Issue by zxFirefly** [SirBlobman/CombatLogX#85]
**Describe the bug**
When a player is tagged and logs out an item, in their inventory is duplicated. I imagine this only works with NPC as instant kill would just drop the items. 

**To Reproduce**
1. Tag player with items in hotbar
2. have player log out
3. log in while timer still going
4. you may find an extra of one of the items.

We've tested with swords, creeper eggs, block, and food

**Expected behavior**
We expected player to log out, npc to be created. If the npc was not killed upon logging in the players inventory would return to normal 

**Minecraft Version**
1.12.2

**CombatLogX Version:**
https://gyazo.com/1ee2f5329c9f0eced43bf79351ac6110

Also I'm unable to damage npc immediately after a player logs out. if there a way to fix that?

**Comment by SirBlobman** [comment]
Please update CombatLogX and reopen this if it's still an issue
