### ISSUE TITLE
bugs..

### ISSUE THREAD

**Issue by xGlenor** [SirBlobman/CombatLogX#86]
Hi, I have some mistakes
https://youtu.be/tMpmG2pIo6I
https://youtu.be/CTOW5ukK84c
https://youtu.be/MrDcsRYdKiY

Errors displayed are during a fight :/

Version plugin: 9.8.1.1

Edit//
It also doesn't work on version 9.9.0.0

**Comment by SirBlobman** [comment]
Please use the the proper bug report template and re-submit this issue.
