### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by lorex14** [SirBlobman/CombatLogX#864]
### Server Implementation

Paper

### Server Version

1.20.6

### Describe the bug

when you drink a potion of strength in battle mode, it has no effect, and also if in my mode you write /kick and kick a player, but resources will not drop from him
version: 1.20.1

### Reproduction Steps

. 

### Expected behaviour

. 

### Screenshots / Videos

. 

### latest log file (if applicable)

. 

### CombatLogX Version

I don't remember the version

**Comment by Olivoz** [comment]
Please follow the issue template.

As for your issues:
1. Configure the CheatPrevention expansions [potions.yml](https://github.com/SirBlobman/CombatLogX/blob/420cf12d722755460e73a76b689209f08162d823/expansion/cheat-prevention/src/main/resources/potions.yml#L7)
2. Enable punishment [on kick in the punish.yml](https://github.com/SirBlobman/CombatLogX/blob/main/plugin/src/main/resources/punish.yml#L9), and make sure to also configure the [kick-ignore-list](https://github.com/SirBlobman/CombatLogX/blob/420cf12d722755460e73a76b689209f08162d823/plugin/src/main/resources/punish.yml#L19-L25) to prevent accidental punishments on server close or other kick actions.
