### ISSUE TITLE
Death message formatting

### ISSUE THREAD

**Issue by ArtelGG** [SirBlobman/CombatLogX#87]
**What Minecraft version are you currently using?**
PaperSpigot 1.14.4-b159

**What version of CombatLogX are you using?**
9.9.0.0

**What is your feature request?**
Add custom death messages/formatting to one of the expansions, such as Notifier.

`&4» &c{victim} &7was killed by &c{attacker}`
`&4» &c{victim} &7was killed by &c{attacker} &7using &e{item}`
`&4» &c{victim} &7was slain by &c{mob}`
`&4» &c{victim} &7fell to their death`
**_(this could go on for a while)_**

I feel like this may sound outside the scope of this plugin, however, I think it'll fit in nicely considering how many options we have currently that aren't technically related to "combat logging".

**Comment by SirBlobman** [comment]
Interesting request, I might make a separate plugin for custom death messages in the future though

**Comment by SirBlobman** [comment]
Custom death messages are now available if you wish to test CombatLogX Beta builds
