### ISSUE TITLE
Getting an error when trying to launch CombatLogX

### ISSUE THREAD

**Issue by KidTechnical** [SirBlobman/CombatLogX#872]
### Server Implementation

Paper

### Server Version

other

### Describe the bug

When I launch my Paper 1.21.3 server CombatLogX gives me this error in the console and doesn't work on the server. https://pastebin.com/LNZHyZtt

### Reproduction Steps

1. Launch a Paper 1.21.3 server with CombatLogX installed (not sure if the error is about the version or something particular with my server, the reproduction steps might not work)
2. See error in console
3. Attempt to use CombatLogX commands and get further errors

### Expected behaviour

I expected no errors in the console and for the plugin to work at all.

### latest log file (if applicable)

https://pastebin.com/HxmF1Sjc

### CombatLogX Version

Running the command gives me an error, but the config says 11.1.0.3.929.

**Comment by Olivoz** [comment]
Looks like your CombatLogX version and BlueSlimeCore version are mismatched. Please use the jars from the same zip file

**Comment by KidTechnical** [comment]
This worked, thank you so much!
