### ISSUE TITLE
[Cheat Prevention] Command warmup in the first x seconds from last combat 

### ISSUE THREAD

**Issue by Drc-DEV** [SirBlobman/CombatLogX#88]
It would be useful to be able to add a **warmup** to certain commands when being executed in the first X seconds after the player's latest combat end. This would prevent instant teleports after the combatlog end, or any other way to instantly escape from the battlefield.

**Example:**

> John puts Mike in combat
> Mike escapes combat with speed potions
> John is right behind him and it's going to hit him again and put Mike in combat
> Mike has a macro for the /spawn command set on his mouse, and right after the combat log ends, he executes the macro and escapes from combat
> John is angry to the server owner and complains

**Comment by ArtelGG** [comment]
If you're using EssentialsX for spawn and teleporting you can add a delay there.

**Comment by Drc-DEV** [comment]
I do not use Essentials, and there may be way more types of commands you'd want to put warmup on. And in your scenario, the warmup would be permanent, not just limited to the first X seconds after latest combat end like I suggested.

**Comment by SirBlobman** [comment]
Sounds like a good feature, but I'm wondering why John would get mad at the server owner if he is the one that let Mike have enough time out of combat to escape him?
