### ISSUE TITLE
Towny SafeZone Freezing

### ISSUE THREAD

**Issue by hasanas83V2001** [SirBlobman/CombatLogX#9]
When you tag a player in a pvp-enabled town, you get frozen for 10 seconds and get spammed with the message "You cannot enter a safezone while in combat" even though it's not a safe zone, since it's pvp-enabled, I have the towny expansion so that's not the issue.
You're an amazing dev and this plugin is great, I really appreciate all the quick support and bugfixes you do!

**Comment by SirBlobman** [comment]
I did test this, do you have any other plugins with SafeZone regions (e.g: WorldGuard)

**Comment by hasanas83V2001** [comment]
Yes we have worldguard

**Comment by SirBlobman** [comment]
This should be fixed in 5.0.0+
Reopen the issue if it is not fixed
