### ISSUE TITLE
Error spammed console

### ISSUE THREAD

**Issue by BeeRando** [SirBlobman/CombatLogX#90]
**Describe the bug**
This error came out of no where and spammed console, and eventually everyone was kicked frmo the server, everyone timed out. 
**Minecraft Version**
 - Do `/clx version` to find out
1.14.4
**CombatLogX Version:**
 - Do `/clx version` to find out
9.8.4.1
**Additional context**
Idk. It just happened once, came out of no where, after everyone relogged it was fine. 

Here's the error.
https://pastebin.com/bEH6XsCf

**Comment by SirBlobman** [comment]
@BeeRando 
1) Your Cheat Prevention potion section is invalid

2) Your version is outdated
