### ISSUE TITLE
Newbie protection time setting does not work?

### ISSUE THREAD

**Issue by uruhara** [SirBlobman/CombatLogX#92]
Hello,
CombatLogX version: 9.9.1.0
Newbie Helper version: 14.3
Issue:
I want a protection for 3 hours so by the plugin settings that should be 10 800 000 ms. But i always get default 3000 ms...
![image](https://user-images.githubusercontent.com/54669393/64068217-35d51200-cc35-11e9-8e95-1dd1b7e691a2.png)
Ty for reply :)

**Comment by SirBlobman** [comment]
Try 9.9.1.1 and tell me if the issue still occurs.

**Comment by uruhara** [comment]
Hello, the problem is now fixed, Thank You!
