### ISSUE TITLE
CombatLogX Still enabled in Disabled worlds

### ISSUE THREAD

**Issue by Waterman1001** [SirBlobman/CombatLogX#94]
**Describe the bug**
I just updated CombatlogX to the latest version, 9.9.1.1, but for some reason.. the part of 'Disabled Worlds' does not work anymore.
Every world suddenly has CombatLog enabled and I have looked very carefully at capital letters. I understand that it is case sensitive.

**To Reproduce**
Hit a player and the player will be in combat log, even though the world is in the 'Disabled Worlds' list.

**Expected behavior**
Combatlog should be disabled in that world.

**Screenshots**
![image](https://user-images.githubusercontent.com/19939623/64494939-7961f880-d293-11e9-8983-8673e5d91cba.png)

**My Latest.log**
[latest (3).log](https://github.com/SirBlobman/CombatLogX/files/3588105/latest.3.log)

**Minecraft and CombatLogX Version**
08.09 23:53:26 [Server] Server thread/INFO Getting version information for CombatLogX...
08.09 23:53:26 [Server] Craft Scheduler Thread - 24/INFO Full Version: git-Spigot-065a373-763e560 (MC: 1.14.4)
08.09 23:53:26 [Server] Craft Scheduler Thread - 24/INFO Bukkit Version: 1.14.4-R0.1-SNAPSHOT
08.09 23:53:26 [Server] Craft Scheduler Thread - 24/INFO Minecraft Version: 1.14.4
08.09 23:53:26 [Server] Craft Scheduler Thread - 24/INFO NMS Version: 1_14_R1
08.09 23:53:26 [Server] Craft Scheduler Thread - 24/INFO CombatLogX by SirBlobman
08.09 23:53:26 [Server] Craft Scheduler Thread - 24/INFO Latest Spigot Version: v9.9.1.1
08.09 23:53:26 [Server] Craft Scheduler Thread - 24/INFO Installed Version: v9.9.1.1
08.09 23:53:26 [Server] Craft Scheduler Thread - 24/INFO Getting expansion versions...
08.09 23:53:26 [Server] Craft Scheduler Thread - 24/INFO WorldGuard Compatibility v14.12
08.09 23:53:26 [Server] Craft Scheduler Thread - 24/INFO Cheat Prevention v14.11

**Comment by SirBlobman** [comment]
Please tell me if this fixes the issue:
https://github.com/SirBlobman/CombatLogX/raw/master/builder/build/CombatLogX-9.9.1.2.zip

**Comment by Waterman1001** [comment]
Thank you so much!
Fixed it!
Works like a charm again :)

**Comment by SirBlobman** [comment]
Good to know, thanks :)
