### ISSUE TITLE
Scoreboard compatiblity 

### ISSUE THREAD

**Issue by fmohican** [SirBlobman/CombatLogX#95]
**Describe the bug**
CombetLogX get overwrited by Titlemanager

**To Reproduce**
1. Install TitleManger & CombatLogX
2. Activate Scoreboard on both plugins.
3. Try to pvp someone, or kill an mob
4. CombatLogX and TitleManger scoreboards will try to "appear" in sametime.

**Expected behavior**
Please check https://github.com/Puharesource/TitleManager/issues/230

**Screenshots**
Please check https://github.com/Puharesource/TitleManager/issues/230 , there are an video with MobArena, its same for CombatLogX

**Minecraft Version**
[16:46:25 INFO]: Full Version: git-Paper-186 (MC: 1.14.4)
[16:46:25 INFO]: Bukkit Version: 1.14.4-R0.1-SNAPSHOT
[16:46:25 INFO]: Minecraft Version: 1.14.4
[16:46:25 INFO]: NMS Version: 1_14_R1

**CombatLogX Version:**
[16:46:59 INFO]: Latest Spigot Version: v9.9.1.1
[16:46:59 INFO]: Installed Version: v9.9.1.1

**Additional context**
https://github.com/Puharesource/TitleManager/issues/230

**Comment by SirBlobman** [comment]
That's just something that cannot be helped. Spigot doesn't have support for two scoreboards so if you want to use the CombatLogX scoreboard you're going to have to disable the TitleManager acoreboard

**Comment by fmohican** [comment]
I don't want to be hater or something, but if you work together with TitleManger Dev, there may be a solution.

**Comment by SirBlobman** [comment]
> I don't want to be hater or something, but if you work together with TitleManger Dev, there may be a solution.
> I mean its posbbile to "temporary" disable TitleManger while CombatLogX shows Scoreboard
> and enable after CombatLogX end the jobs.

I'll look into it, if it's possible you should see an update soon
