### ISSUE TITLE
CombatLogX is not working

### ISSUE THREAD

**Issue by Dzgs** [SirBlobman/CombatLogX#99]
**Describe the bug**
CombatLogX gives an error and it's not working.

**To Reproduce**
I just uploaded the plugin and it's not working.

**Screenshots**
![image](https://user-images.githubusercontent.com/52612280/65130780-cb7aea80-da06-11e9-80fb-a23c1062365a.png)

**Minecraft Version**
 git-Paper-645 (MC: 1.13.2)

**CombatLogX Version:**
 The command is not working ,but using the latest version (9.9.1.4)

**Comment by Olivoz** [comment]
Try to reset the language file.
If it doesn't help you can join the discord for faster support.

**Comment by SirBlobman** [comment]
I made a mistake on line 93 of `language.yml`. It has too many spaces. I will fix this soon

**Comment by SirBlobman** [comment]
Fixed in 9.9.1.7
